"use client"
import { useRouter } from "next/navigation"
import { useState } from "react"
import type { Account } from "@/lib/afd/contracts"
import { BrowserAfdError, mutateAfd } from "@/lib/afd/browser-client"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { StatusPill } from "@/components/desk/status-pill"
import { EmptyState } from "@/components/desk/page-header"

export function AccountSettings({ accounts }: { accounts: Account[] }) { const router = useRouter(); const [aliases, setAliases] = useState(Object.fromEntries(accounts.map((a) => [a.public_id, a.account_alias]))); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); async function act(path: string, body?: object) { setBusy(path); setError(""); try { await mutateAfd(path, "PUT", body); router.refresh() } catch (caught) { setError(caught instanceof BrowserAfdError ? caught.message : "The account change was not confirmed.") } finally { setBusy("") } } return <div className="space-y-4">{error && <p role="alert" className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{error}</p>}{accounts.map((account) => <Card key={account.public_id}><CardHeader><div className="flex items-center justify-between"><CardTitle>{account.account_name || account.account_alias}</CardTitle><StatusPill label={account.environment.toUpperCase()} tone={account.environment === "live" ? "bad" : "good"} /></div></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">Alias</p><div className="mt-1 flex gap-2"><Input value={aliases[account.public_id]} onChange={(e) => setAliases((current) => ({ ...current, [account.public_id]: e.target.value }))} aria-label={`Alias for ${account.account_alias}`} /><Button size="sm" variant="outline" onClick={() => act(`broker/accounts/${account.public_id}/alias`, { alias: aliases[account.public_id] })} disabled={Boolean(busy)}>Save</Button></div></div><Datum label="Currency" value={account.currency || "Unavailable"} /><Datum label="Bound profiles" value={String(account.profiles.length)} /><Datum label="Availability" value={account.available && account.locally_enabled ? "Enabled" : "Disabled"} /></div><div className="mt-5 flex gap-2">{!account.is_default_analysis && <Button size="sm" variant="outline" onClick={() => act(`broker/accounts/${account.public_id}/default`)} disabled={Boolean(busy)}>Set as default</Button>}{account.is_default_analysis && <StatusPill label="Default account" tone="good" />}<Button size="sm" variant="ghost" className="text-red-600" onClick={() => act(`broker/accounts/${account.public_id}/disable`)} disabled={Boolean(busy)}>Disable account</Button></div></CardContent></Card>)}{!accounts.length && <EmptyState title="No accounts available" description="Connect TradeLocker and refresh account discovery first." />}</div> }
function Datum({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-sm font-medium">{value}</p></div> }
