"use client"
import { useRouter } from "next/navigation"
import { useState } from "react"
import type { Account } from "@/lib/afd/contracts"
import { accountContext, accountTitle } from "@/lib/afd/display"
import { mutateAfd } from "@/lib/afd/browser-client"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { StatusPill } from "@/components/desk/status-pill"
import { EmptyState } from "@/components/desk/page-header"
export function AccountSettings({accounts}:{accounts:Account[]}){const router=useRouter();const [names,setNames]=useState(Object.fromEntries(accounts.map(a=>[a.public_id,a.nickname??""])));const [busy,setBusy]=useState("");async function act(path:string,body?:object){setBusy(path);try{await mutateAfd(path,"PUT",body);router.refresh()}finally{setBusy("")}}return <div className="space-y-4">{accounts.map(account=><Card key={account.public_id}><CardHeader><div className="flex justify-between"><div><CardTitle>{accountTitle(account)}</CardTitle><p className="text-sm text-muted-foreground">{accountContext(account)}{account.nickname?` · ${account.nickname}`:""}</p></div>{account.is_default_analysis&&<StatusPill label="Primary Account" tone="good"/>}</div></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">Nickname</p><div className="mt-1 flex gap-2"><Input value={names[account.public_id]} onChange={e=>setNames(v=>({...v,[account.public_id]:e.target.value}))} placeholder="Optional deliberate nickname"/><Button size="sm" variant="outline" onClick={()=>act(`broker/accounts/${account.public_id}/alias`,{alias:names[account.public_id]})}>Save</Button></div></div><Datum label="Currency" value={account.currency??"Unavailable"}/><Datum label="Profiles" value={String(account.profiles.length)}/><Datum label="Availability" value={account.available&&account.locally_enabled?"Available":"Unavailable"}/></div><div className="mt-5 flex gap-2">{!account.is_default_analysis&&<Button size="sm" variant="outline" disabled={Boolean(busy)||!account.available} onClick={()=>act(`broker/accounts/${account.public_id}/default`)}>Make Primary Account</Button>}<Button size="sm" variant="ghost" className="text-red-600" onClick={()=>act(`broker/accounts/${account.public_id}/disable`)}>Disable account</Button></div></CardContent></Card>)}{!accounts.length&&<EmptyState title="No trading accounts" description="Add a trading connection to discover durable accounts."/>}</div>}
function Datum({label,value}:{label:string;value:string}){return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm">{value}</p></div>}
