"use client"
import Link from "next/link"
import { usePathname } from "next/navigation"
import { useState } from "react"
import { Activity,Bell,Bot,CalendarClock,ChevronDown,Gauge,LineChart,Menu,PanelLeftClose,PanelLeftOpen,Settings,ShieldCheck,SlidersHorizontal,X } from "lucide-react"
import type { Account } from "@/lib/afd/contracts"
import { cn } from "@/lib/utils"
import { ThemeToggle } from "@/components/theme-toggle"
import { Button } from "@/components/ui/button"
import { StatusPill } from "./status-pill"
import { AccountProvider } from "./account-provider"
import { AccountSwitcher } from "./account-switcher"
import { CommandPalette } from "./command-palette"
const navigation=[["Dashboard","/dashboard",Gauge],["Markets","/markets",LineChart],["Trade","/trade",SlidersHorizontal],["Autonomous","/autonomous",Bot],["Schedules","/schedules",CalendarClock],["Activity","/activity",Activity],["Settings","/settings",Settings]] as const
function DeskNav({close,collapsed=false}:{close?:()=>void;collapsed?:boolean}){const pathname=usePathname();return <nav aria-label="Primary navigation" className="space-y-1">{navigation.map(([label,href,Icon])=>{const active=pathname===href||(href!=="/dashboard"&&pathname.startsWith(`${href}/`));return <Link key={href} href={href} title={collapsed?label:undefined} aria-label={collapsed?label:undefined} onClick={close} aria-current={active?"page":undefined} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-muted-foreground hover:bg-accent hover:text-foreground focus-visible:ring-2",collapsed&&"justify-center px-2",active&&"bg-accent text-foreground")}><Icon className="h-4 w-4 shrink-0"/>{!collapsed&&label}</Link>})}</nav>}
export function AppShell({children,user,accounts,backendOnline,brokerReady}:{children:React.ReactNode;user:{name?:string|null;email?:string|null};accounts:Account[];backendOnline:boolean;brokerReady:boolean}){return <AccountProvider accounts={accounts}><ShellContent user={user} backendOnline={backendOnline} brokerReady={brokerReady}>{children}</ShellContent></AccountProvider>}
function ShellContent({children,user,backendOnline,brokerReady}:{children:React.ReactNode;user:{name?:string|null;email?:string|null};backendOnline:boolean;brokerReady:boolean}){const [open,setOpen]=useState(false);const [collapsed,setCollapsed]=useState(false);return <div className="min-h-screen bg-background"><aside className={cn("fixed inset-y-0 left-0 z-40 hidden border-r bg-card lg:flex lg:flex-col",collapsed?"w-20":"w-64")}><Brand collapsed={collapsed}/><div className="flex-1 overflow-y-auto p-4"><DeskNav collapsed={collapsed}/></div>{!collapsed&&<div className="border-t p-4 text-xs text-muted-foreground"><div className="mb-2 flex justify-between"><span>Application API</span><StatusPill label={backendOnline?"Available":"Unavailable"} tone={backendOnline?"good":"bad"}/></div><div className="flex justify-between"><span>Trading connection</span><StatusPill label={brokerReady?"Connected":"Needs Attention"} tone={brokerReady?"good":"warn"}/></div></div>}<Button variant="ghost" size="icon" className="mb-3 self-center" onClick={()=>setCollapsed(!collapsed)} aria-label={collapsed?"Expand sidebar":"Collapse sidebar"}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</Button></aside>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/60" aria-label="Close navigation" onClick={()=>setOpen(false)}/><aside className="relative h-full w-72 border-r bg-card"><div className="flex items-center justify-between"><Brand/><Button variant="ghost" size="icon" onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></Button></div><div className="p-4"><DeskNav close={()=>setOpen(false)}/></div></aside></div>}<div className={collapsed?"lg:pl-20":"lg:pl-64"}><header className="sticky top-0 z-30 flex min-h-16 items-center gap-2 border-b bg-background/90 px-3 backdrop-blur sm:px-6"><Button className="lg:hidden" variant="ghost" size="icon" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></Button><div className="min-w-0 flex-1"><AccountSwitcher/></div><CommandPalette/><Button variant="ghost" size="icon" aria-label="Notifications"><Bell className="h-4 w-4"/></Button><ThemeToggle/><div className="hidden border-l pl-3 sm:block"><p className="max-w-40 truncate text-sm font-medium">{user.name??user.email??"Trader"}</p><Link href="/auth/logout" className="text-xs text-muted-foreground">Sign out</Link></div><ChevronDown className="hidden h-4 w-4 text-muted-foreground sm:block"/></header><main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">{children}</main></div></div>}
function Brand({collapsed=false}:{collapsed?:boolean}){return <Link href="/dashboard" aria-label="Agentic Trading Desk dashboard" className={cn("flex h-16 items-center gap-3 px-5",collapsed&&"justify-center px-2")}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-emerald-600 text-white"><ShieldCheck className="h-5 w-5"/></span>{!collapsed&&<span><strong className="block text-sm">Agentic Trading Desk</strong><span className="block text-[10px] text-muted-foreground">Trading operations workspace</span></span>}</Link>}
