import Link from "next/link"
import { AlertTriangle, Bot, CalendarClock, Radio, ShieldAlert, Waypoints } from "lucide-react"
import { authenticatedBackendClient } from "@/lib/afd/backend"
import { loadDashboardData } from "@/lib/afd/dashboard-data"
import { PageHeader, EmptyState } from "@/components/desk/page-header"
import { StatusPill } from "@/components/desk/status-pill"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export const metadata = { title: "Dashboard" }
const format = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not recorded"
export default async function DashboardPage() {
  let data
  try { data = await loadDashboardData(await authenticatedBackendClient()) } catch { data = await loadDashboardData(async () => { throw new Error("unavailable") }) }
  const selected = data.accounts.find((a) => a.is_default_analysis) ?? data.accounts[0]
  const activeSchedules = data.schedules.filter((s) => s.enabled).length
  const setupRequired = !data.connections.length || data.status?.status !== "ready"
  return <div className="space-y-7"><PageHeader eyebrow="Operations desk" title="Trading command center" description="Verified broker, worker, profile, schedule, and autonomous safety state from the Agentic Forex Desk backend." actions={<StatusPill label={data.coreUnavailable ? "Backend degraded" : "Backend connected"} tone={data.coreUnavailable ? "bad" : "good"} />} />
    {Object.keys(data.errors).length > 0 && <div role="status" className="flex gap-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm"><AlertTriangle className="h-5 w-5 shrink-0 text-amber-600" /><div><strong>Some operational data is unavailable.</strong><p className="mt-1 text-muted-foreground">Loaded sections are preserved. Unavailable sections default to blocked: {Object.keys(data.errors).join(", ")}.</p></div></div>}
    {setupRequired && !data.coreUnavailable && <div className="flex flex-col justify-between gap-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-5 sm:flex-row sm:items-center"><div><strong>Broker setup required</strong><p className="mt-1 text-sm text-muted-foreground">Connect TradeLocker and select an account before configuring execution.</p></div><Button asChild><Link prefetch={false} href={data.connections.length ? "/select-account" : "/connect-tradelocker"}>{data.connections.length ? "Select account" : "Connect TradeLocker"}</Link></Button></div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Waypoints} label="Selected account" value={selected?.account_alias ?? "Unavailable"} detail={selected ? selected.environment.toUpperCase() : "Trading blocked"} /><Metric icon={Bot} label="Enabled profiles" value={String(data.profiles.filter((p) => p.enabled).length)} detail={`${data.profiles.length} total`} /><Metric icon={ShieldAlert} label="Global kill switch" value={data.controls.global_autonomous_kill_switch ? "Enabled" : "Disabled"} detail={data.controls.global_autonomous_kill_switch ? "New submissions blocked" : "Backend confirmed off"} danger={!data.controls.global_autonomous_kill_switch} /><Metric icon={CalendarClock} label="Active schedules" value={String(activeSchedules)} detail={`${data.schedules.length} configured`} /></section>
    <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Today’s outcomes</CardTitle><StatusPill label={data.daily.date || "UTC"} /></div></CardHeader><CardContent className="grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(data.daily.outcomes).map(([key, count]) => <div key={key} className="rounded-lg border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">{key.replaceAll("_", " ")}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{count}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Radio className="h-4 w-4" /> Worker health</CardTitle></CardHeader><CardContent><StatusPill label={data.worker.status} tone={data.worker.status === "healthy" ? "good" : "warn"} /><div className="mt-4 space-y-2">{data.worker.workers.map((worker) => <div className="flex justify-between text-sm" key={worker.worker_id}><span className="truncate">{worker.worker_id}</span><span className="text-muted-foreground">{worker.healthy ? "Healthy" : "Stale"}</span></div>)}{!data.worker.workers.length && <p className="text-sm text-muted-foreground">No worker heartbeat is available. Durable scheduling cannot be verified.</p>}</div></CardContent></Card></section>
    <section className="grid gap-5 xl:grid-cols-3"><Card><CardHeader><CardTitle>Recent autonomous runs</CardTitle></CardHeader><CardContent className="space-y-3">{data.runs.slice(0, 5).map((run) => <Link href="/activity" key={run.run_id} className="flex items-center justify-between rounded-lg border p-3 hover:bg-accent"><span><strong className="block text-sm">{run.outcome ?? "Unknown outcome"}</strong><span className="text-xs text-muted-foreground">{run.chosen_instrument ?? "No instrument selected"}</span></span><span className="text-xs text-muted-foreground">{format(run.started_at)}</span></Link>)}{!data.runs.length && <EmptyState title="No autonomous runs" description="Backend audit history will appear here after a scheduled decision run." />}</CardContent></Card><Card><CardHeader><CardTitle>Recent demo executions</CardTitle></CardHeader><CardContent className="space-y-3">{data.executions.slice(0, 5).map((execution) => <Link href="/activity" key={execution.id} className="block rounded-lg border p-3 hover:bg-accent"><strong className="block text-sm">{execution.action_type ?? execution.symbol ?? "Demo execution"}</strong><span className="text-xs text-muted-foreground">{execution.state ?? execution.result ?? "Unknown"} · {format(execution.created_at)}</span></Link>)}{!data.executions.length && <EmptyState title="No demo executions" description="Confirmed demo execution records will appear here." />}</CardContent></Card><Card><CardHeader><CardTitle>Upcoming schedules</CardTitle></CardHeader><CardContent className="space-y-3">{data.schedules.filter((s) => s.enabled).slice(0, 5).map((schedule) => <Link href="/schedules" key={schedule.id} className="flex items-center justify-between rounded-lg border p-3 hover:bg-accent"><span><strong className="block text-sm">{schedule.profile_ref}</strong><span className="text-xs text-muted-foreground">{schedule.timezone}</span></span><span className="text-xs text-muted-foreground">{format(schedule.next_run_at)}</span></Link>)}{!activeSchedules && <EmptyState title="No active schedules" description="Create a schedule from an execution profile to run durable autonomous decisions." />}</CardContent></Card></section>
  </div>
}
function Metric({ icon: Icon, label, value, detail, danger }: { icon: typeof Bot; label: string; value: string; detail: string; danger?: boolean }) { return <Card><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p><p className={danger ? "mt-1 text-xs text-red-600" : "mt-1 text-xs text-muted-foreground"}>{detail}</p></div><span className="rounded-lg bg-muted p-2"><Icon className="h-4 w-4" /></span></CardContent></Card> }
