"use client"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useState } from "react"
import type { Connection } from "@/lib/afd/contracts"
import { mutateAfd, BrowserAfdError } from "@/lib/afd/browser-client"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { StatusPill } from "@/components/desk/status-pill"
import { EmptyState } from "@/components/desk/page-header"

export function BrokerSettings({ connections }: { connections: Connection[] }) { const router = useRouter(); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); async function act(path: string, method: "POST" | "PUT" | "DELETE") { setBusy(path); setError(""); try { await mutateAfd(path, method); router.refresh() } catch (caught) { setError(caught instanceof BrowserAfdError ? caught.message : "The backend did not confirm this change.") } finally { setBusy("") } } return <div className="space-y-4">{error && <p role="alert" className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end"><Button asChild><Link href="/connect-tradelocker?new=1">Add connection</Link></Button></div>{connections.map((connection) => <Card key={connection.public_id}><CardHeader><div className="flex items-center justify-between"><div><CardTitle>{connection.label || connection.server}</CardTitle><p className="mt-1 text-sm text-muted-foreground">TradeLocker · {connection.server}</p></div><StatusPill label={connection.environment.toUpperCase()} tone={connection.environment === "live" ? "bad" : "good"} /></div></CardHeader><CardContent><dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-xs text-muted-foreground">State</dt><dd className="mt-1">{connection.enabled ? "Enabled" : "Reauthentication required"}</dd></div><div><dt className="text-xs text-muted-foreground">Accounts</dt><dd className="mt-1">{connection.account_count}</dd></div><div><dt className="text-xs text-muted-foreground">Last verified</dt><dd className="mt-1">{connection.last_verified_at ?? "Not recorded"}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => act(`broker/tradelocker/discover-accounts?connection_id=${encodeURIComponent(connection.public_id)}`, "POST")} disabled={Boolean(busy)}>Refresh accounts</Button><Button asChild size="sm" variant="outline"><Link href={`/connect-tradelocker?connection_id=${encodeURIComponent(connection.public_id)}`}>Reauthenticate</Link></Button><Button size="sm" variant="outline" onClick={() => act(`broker/connections/${connection.public_id}/disable`, "PUT")} disabled={Boolean(busy)}>Disable connection</Button><Button size="sm" variant="ghost" className="text-red-600" onClick={() => act("broker/tradelocker", "DELETE")} disabled={Boolean(busy)}>Disconnect legacy default</Button></div></CardContent></Card>)}{!connections.length && <EmptyState title="No broker connections" description="Add TradeLocker to discover accounts. Credentials remain encrypted in the existing backend." action={<Button asChild><Link href="/connect-tradelocker">Connect TradeLocker</Link></Button>} />}</div> }
