"use client"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useState } from "react"
import type { Connection } from "@/lib/afd/contracts"
import { formatEnum } from "@/lib/afd/display"
import { mutateAfd } from "@/lib/afd/browser-client"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { StatusPill } from "@/components/desk/status-pill"
import { EmptyState } from "@/components/desk/page-header"
export function BrokerSettings({connections}:{connections:Connection[]}){const router=useRouter();const [busy,setBusy]=useState("");async function act(path:string,method:"POST"|"PUT"|"DELETE"){setBusy(path);try{await mutateAfd(path,method);router.refresh()}finally{setBusy("")}}async function remove(){if(window.confirm("Remove this TradeLocker trading connection and its stored account access?"))await act("broker/tradelocker","DELETE")}return <div className="space-y-4"><div className="flex justify-end"><Button asChild><Link href="/connect-tradelocker?new=1">Add Trading Connection</Link></Button></div>{connections.map(connection=><Card key={connection.public_id}><CardHeader><div className="flex justify-between"><div><CardTitle>{connection.broker_name||connection.server||"HeroFX"}</CardTitle><p className="text-sm text-muted-foreground">Connected through {connection.platform_name||"TradeLocker"}</p></div><StatusPill label={formatEnum(connection.environment)} tone={connection.environment==="live"?"bad":"good"}/></div></CardHeader><CardContent><dl className="grid gap-3 text-sm sm:grid-cols-3"><Datum label="Status" value={connection.enabled?"Connected":"Reauthentication required"}/><Datum label="Account count" value={String(connection.account_count)}/><Datum label="Last verified" value={connection.last_verified_at?new Date(connection.last_verified_at).toLocaleString():"Not recorded"}/></dl><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>act(`broker/tradelocker/discover-accounts?connection_id=${encodeURIComponent(connection.public_id)}`,"POST")}>Refresh accounts</Button><Button asChild size="sm" variant="outline"><Link href={`/connect-tradelocker?connection_id=${encodeURIComponent(connection.public_id)}`}>Reauthenticate</Link></Button><Button size="sm" variant="ghost" className="text-red-600" disabled={Boolean(busy)} onClick={()=>void remove()}>Remove Connection</Button></div></CardContent></Card>)}{!connections.length&&<EmptyState title="No trading connections" description="Add TradeLocker to discover HeroFX accounts." action={<Button asChild><Link href="/connect-tradelocker">Add Trading Connection</Link></Button>}/>}</div>}
function Datum({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1">{value}</dd></div>}
