"use client"
import { FormEvent, useState } from "react"
import { useRouter } from "next/navigation"
import type { ProfileSummary, Schedule } from "@/lib/afd/contracts"
import { formatEnum } from "@/lib/afd/display"
import { BrowserAfdError, mutateAfd } from "@/lib/afd/browser-client"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { StatusPill } from "@/components/desk/status-pill"
import { EmptyState } from "@/components/desk/page-header"
const DAYS=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]
const when=(value?:string)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Not scheduled"
export function ScheduleManager({initialSchedules,profiles}:{initialSchedules:Schedule[];profiles:ProfileSummary[]}){const router=useRouter();const [dialog,setDialog]=useState<{schedule?:Schedule}|null>(null);const [type,setType]=useState("market_session");const [busy,setBusy]=useState("");const [error,setError]=useState("");async function act(path:string,method:"POST"|"PUT"|"DELETE",body?:object){setBusy(path);setError("");try{await mutateAfd(path,method,body);router.refresh()}catch(e){setError(e instanceof BrowserAfdError?e.message:"The schedule change was not confirmed.")}finally{setBusy("")}}async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const schedule=dialog?.schedule;const recurrence={type,days:data.getAll("days"),times:[String(data.get("time"))],sessions:data.getAll("sessions"),start_time:data.get("start"),end_time:data.get("end"),interval_minutes:Number(data.get("interval"))};const payload={timezone:data.get("timezone"),recurrence,maximum_lateness_seconds:Number(data.get("lateness")),enabled:true};await act(schedule?`autonomous-schedules/${schedule.id}`:`execution-profiles/${data.get("profile")}/autonomy/schedule`,schedule?"PUT":"POST",payload);setDialog(null)}function open(schedule?:Schedule){setType(schedule?.recurrence?.type??"market_session");setDialog({schedule})}
return <div className="space-y-5">{error&&<p role="alert" className="rounded border border-red-500/30 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end"><Button onClick={()=>open()} disabled={!profiles.length}>Create schedule</Button></div>{initialSchedules.map(schedule=>{const profile=profiles.find(p=>p.public_id===schedule.profile_ref);return <Card key={schedule.id}><CardHeader><div className="flex justify-between"><div><CardTitle>{profile?.name??schedule.profile_ref}</CardTitle><p className="text-sm text-muted-foreground">{formatEnum(schedule.schedule_type??schedule.recurrence?.type??"daily")} · {schedule.timezone}</p></div><StatusPill label={schedule.enabled?"Active":"Paused"} tone={schedule.enabled?"good":"warn"}/></div></CardHeader><CardContent><p className="text-sm font-medium">Next five runs</p><ol className="mt-2 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-5">{(schedule.next_run_times??[]).map(value=><li className="rounded border p-2" key={value}>{when(value)}</li>)}</ol><div className="mt-4 flex gap-2"><Button size="sm" variant="outline" disabled={Boolean(busy)} onClick={()=>act(`autonomous-schedules/${schedule.id}/${schedule.enabled?"pause":"resume"}`,"POST")}>{schedule.enabled?"Pause":"Resume"}</Button><Button size="sm" variant="outline" onClick={()=>open(schedule)}>Edit</Button><Button size="sm" variant="ghost" className="text-red-600" onClick={()=>act(`autonomous-schedules/${schedule.id}`,"DELETE")}>Delete</Button></div></CardContent></Card>})}{!initialSchedules.length&&<EmptyState title="No schedules" description="Create a structured schedule for an execution profile."/>}
<Dialog open={Boolean(dialog)} onOpenChange={value=>!value&&setDialog(null)}><DialogContent><form onSubmit={save}><DialogHeader><DialogTitle>{dialog?.schedule?"Edit schedule":"Create schedule"}</DialogTitle><DialogDescription>Times use your selected browser timezone and remain market-aware.</DialogDescription></DialogHeader><div className="my-5 space-y-4">{!dialog?.schedule&&<SelectField label="Profile" name="profile" options={profiles.map(p=>[p.public_id,p.name])}/>}<div><Label>Schedule type</Label><select name="type" value={type} onChange={e=>setType(e.target.value)} className="mt-1 h-10 w-full rounded border bg-background px-3">{["market_session","recurring_interval","daily","weekly","custom"].map(v=><option key={v} value={v}>{formatEnum(v)}</option>)}</select></div><div><Label>Timezone</Label><Input name="timezone" defaultValue={dialog?.schedule?.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone} required/></div>{type==="market_session"&&<div><Label>Market sessions</Label><div className="flex flex-wrap gap-3">{["asia","london","new_york","overlap"].map(v=><label key={v}><input type="checkbox" name="sessions" value={v} defaultChecked={v==="london"}/> {formatEnum(v)}</label>)}</div></div>}{type==="recurring_interval"?<div className="grid grid-cols-3 gap-2"><Input type="time" name="start" defaultValue="08:00"/><Input type="time" name="end" defaultValue="17:00"/><Input type="number" name="interval" min={15} max={1440} defaultValue={60}/></div>:type!=="market_session"&&<div><Label>Run time</Label><Input type="time" name="time" defaultValue={dialog?.schedule?.recurrence?.times?.[0]??"09:00"}/></div>}{["weekly","custom","market_session","recurring_interval"].includes(type)&&<div><Label>Days</Label><div className="flex flex-wrap gap-2">{DAYS.map(day=><label key={day} className="text-sm"><input type="checkbox" name="days" value={day} defaultChecked={!day.startsWith("s")}/> {formatEnum(day)}</label>)}</div></div>}<div><Label>Maximum lateness (seconds)</Label><Input type="number" name="lateness" min={30} max={3600} defaultValue={dialog?.schedule?.maximum_lateness_seconds??600}/></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setDialog(null)}>Cancel</Button><Button disabled={Boolean(busy)}>Save schedule</Button></DialogFooter></form></DialogContent></Dialog></div>}
function SelectField({label,name,options}:{label:string;name:string;options:Array<[string,string]>}){return <div><Label>{label}</Label><select name={name} className="mt-1 h-10 w-full rounded border bg-background px-3">{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div>}
