import { AlertTriangle } from "lucide-react"
import { PageHeader, EmptyState } from "@/components/desk/page-header"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export const metadata = { title: "Manual trade" }
export default function TradePage() {
  return <div className="space-y-7"><PageHeader eyebrow="Capability preview" title="Manual trade" description="A production-ready layout for order preview and submission once canonical authenticated REST contracts are available." /><div className="flex gap-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm"><AlertTriangle className="h-5 w-5 shrink-0 text-amber-600" /><div><strong>Manual execution is unavailable.</strong><p className="mt-1 text-muted-foreground">The backend does not currently expose authenticated web contracts for positions, pending orders, order previews, or manual submission. No browser or MCP fallback is used.</p></div></div><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><CardTitle>Order ticket</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Symbol" placeholder="Select a broker instrument" /><div className="grid grid-cols-2 gap-3"><Button variant="outline" disabled>Buy</Button><Button variant="outline" disabled>Sell</Button></div><div className="grid grid-cols-2 gap-3"><Field label="Order type" value="Market" readOnly /><Field label="Quantity" placeholder="Unavailable" /></div><div className="grid grid-cols-2 gap-3"><Field label="Stop loss" placeholder="Unavailable" /><Field label="Take profit" placeholder="Unavailable" /></div><Field label="Risk-based sizing" value="Backend capability required" readOnly /><div className="rounded-lg bg-muted p-3 text-sm"><div className="flex justify-between"><span>Estimated reward-to-risk</span><strong>Unavailable</strong></div></div><Button className="w-full" disabled>Preview order — unavailable</Button><Button variant="outline" className="w-full" disabled>Confirm and submit — unavailable</Button></CardContent></Card><div className="space-y-5"><Card><CardHeader><CardTitle>Open positions</CardTitle></CardHeader><CardContent><EmptyState title="Position API not exposed" description="Positions will appear here when the backend adds an authenticated REST contract." /></CardContent></Card><div className="grid gap-5 md:grid-cols-2"><Card><CardHeader><CardTitle>Pending orders</CardTitle></CardHeader><CardContent><EmptyState title="Unavailable" description="No pending-order endpoint exists." /></CardContent></Card><Card><CardHeader><CardTitle>Recent orders</CardTitle></CardHeader><CardContent><EmptyState title="Unavailable" description="No canonical order-history endpoint exists." /></CardContent></Card></div></div></div></div>
}
function Field(props: React.ComponentProps<typeof Input> & { label: string }) { const { label, ...rest } = props; return <div><Label>{label}</Label><Input className="mt-1.5" disabled {...rest} /></div> }
