"use client"
import { AlertTriangle } from "lucide-react"
import { useAccountContext } from "@/components/desk/account-provider"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs"
const stages=["Build Order","Review","Confirm","Submitted","Reconciled"]
export function TradeWorkspace(){const {selected}=useAccountContext();const live=selected?.environment==="live";return <div className="space-y-5"><div className={`flex gap-3 rounded-xl border p-4 text-sm ${live?"border-red-500 bg-red-500/10":"border-amber-500/30 bg-amber-500/10"}`}><AlertTriangle className="h-5 w-5"/><div><strong>{live?"Live account selected — execution disabled":"Trade submission is not yet available"}</strong><p className="text-muted-foreground">No MCP or browser-to-broker fallback is used. Values remain unavailable until the backend exposes authoritative order contracts.</p></div></div><ol className="grid grid-cols-5 gap-2 text-center text-xs">{stages.map((stage,index)=><li className={`rounded border p-2 ${index===0?"bg-accent font-semibold":"text-muted-foreground"}`} key={stage}>{stage}</li>)}</ol><Tabs defaultValue="ticket"><TabsList className="grid w-full grid-cols-4"><TabsTrigger value="ticket">Order Ticket</TabsTrigger><TabsTrigger value="positions">Open Positions</TabsTrigger><TabsTrigger value="pending">Pending Orders</TabsTrigger><TabsTrigger value="history">Order History</TabsTrigger></TabsList><TabsContent value="ticket"><div className="grid gap-5 xl:grid-cols-[1fr_.8fr]"><Card><CardHeader><CardTitle>Build Order</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="Symbol"/><Field label="Direction"/><Field label="Order type"/><Field label="Quantity"/><Field label="Stop loss"/><Field label="Take profit"/><Button className="sm:col-span-2" disabled>Review order — unavailable</Button></CardContent></Card><Card><CardHeader><div className="flex justify-between"><CardTitle>Review</CardTitle>{selected&&<Badge variant={live?"destructive":"secondary"}>{selected.environment.toUpperCase()}</Badge>}</div></CardHeader><CardContent className="space-y-3"><Datum label="Trading account" value={selected?.accountNumber??"No account selected"}/><Datum label="Broker" value={selected?.broker??"Unavailable"}/><Datum label="Environment" value={selected?.environment??"Unavailable"}/><Datum label="Symbol" value="Not selected"/><Datum label="Direction" value="Not selected"/><Datum label="Order type" value="Not selected"/><Datum label="Quantity" value="Unavailable"/><Datum label="Estimated risk" value="Unavailable"/><Datum label="Stop loss" value="Unavailable"/><Datum label="Take profit" value="Unavailable"/><Datum label="R:R" value="Unavailable"/><Datum label="Margin estimate" value="Unavailable"/></CardContent></Card></div></TabsContent>{["positions","pending","history"].map(tab=><TabsContent value={tab} key={tab}><Card><CardContent className="p-10 text-center text-sm text-muted-foreground">Authenticated {tab} data is not exposed by the backend. No data is fabricated.</CardContent></Card></TabsContent>)}</Tabs></div>}
function Field({label}:{label:string}){return <div><Label>{label}</Label><Input disabled placeholder="Unavailable"/></div>}
function Datum({label,value}:{label:string;value:string}){return <div className="flex justify-between border-b pb-2 text-sm"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div>}
