"use client"
import { useEffect,useMemo,useRef,useState } from "react"
import { useSearchParams } from "next/navigation"
import { AlertTriangle,Check,Minus,Plus,Search,X } from "lucide-react"
import { useAccountContext } from "@/components/desk/account-provider"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs"
import { BrowserAfdError,browserAfdFetch } from "@/lib/afd/browser-client"
import { activeCalculation,entryForSide,previewExpired,protectionMessage,stepQuantity,type Side,type TargetMode,type ProtectionMode } from "./ticket-model"

const stages=["Build Order","Review","Confirm","Submitted","Reconciled"]
type Protection={mode:ProtectionMode;value:string};type Target={mode:TargetMode;value:string}
type Calculation={
  quote:{bid:number|null;ask:number|null;spread:number|null;timestamp:string|null;source:string;stale:boolean};entry_price:number|null;entry_side:"Ask"|"Bid"|null;
  quantity:{value:number;unit:string;minimum:number;maximum:number|null;step:number};pip_size:number;tick_size:number;price_precision:number;contract_size:number;
  pip_value:{value:number;currency:string|null}|null;stop_loss:{price:number|null;distance_pips:number|null;estimated_loss:number|null;risk_percent:number|null}|null;
  take_profit:{price:number|null;distance_pips:number|null;estimated_profit:number|null;reward_to_risk:number|null}|null;
  notional_exposure:number|null;margin_estimate:number|null;warnings:string[];blocking_reasons:string[];
  capabilities:{calculation:boolean;preview:boolean;submission:boolean}
}
type Preview={calculation:Calculation;expires_at:string;preview_id:string}
type Instrument={canonical_id:string;display_symbol:string;description:string;asset_class:string;exchange?:string|null}
type SearchData={results:Instrument[]}
type Ticket={accountId:string;instrument:string;side:Side;orderType:"market"|"limit"|"stop";quantity:number;stopLoss:Protection;takeProfit:Target;calculation:Calculation|null;preview:Preview|null}

export function TradeWorkspace(){
  const {selected}=useAccountContext();const params=useSearchParams();const initial=params.get("instrument")||"";const sequence=useRef(0)
  const [ticket,setTicket]=useState<Ticket>({accountId:selected?.publicRef??"",instrument:initial,side:"buy",orderType:"market",quantity:.5,stopLoss:{mode:"price",value:""},takeProfit:{mode:"price",value:""},calculation:null,preview:null})
  const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [symbolQuery,setSymbolQuery]=useState(initial?initial.split(":").at(-1)??initial:"");const [symbolResults,setSymbolResults]=useState<Instrument[]>([]);const [symbolSearching,setSymbolSearching]=useState(false);const [symbolSearched,setSymbolSearched]=useState(false);const live=selected?.environment==="live"
  useEffect(()=>{setTicket(current=>({...current,accountId:selected?.publicRef??"",calculation:null,preview:null}))},[selected?.publicRef])
  useEffect(()=>{
    const query=symbolQuery.trim();if(!query){setSymbolResults([]);setSymbolSearched(false);return}
    const controller=new AbortController();const timer=setTimeout(async()=>{setSymbolSearching(true);try{const data=await browserAfdFetch<SearchData>(`markets/search?q=${encodeURIComponent(query)}`,{signal:controller.signal});setSymbolResults(data.results??[]);setSymbolSearched(true)}catch{if(!controller.signal.aborted){setSymbolResults([]);setSymbolSearched(true)}}finally{if(!controller.signal.aborted)setSymbolSearching(false)}},250)
    return()=>{clearTimeout(timer);controller.abort()}
  },[symbolQuery])
  const payload=useMemo(()=>({account_id:ticket.accountId,instrument_id:ticket.instrument,side:ticket.side,order_type:ticket.orderType,
    quantity:{value:ticket.quantity,unit:"lot"},stop_loss:ticket.stopLoss.value?{mode:ticket.stopLoss.mode,value:Number(ticket.stopLoss.value)}:null,
    take_profit:ticket.takeProfit.value?{mode:ticket.takeProfit.mode,value:Number(ticket.takeProfit.value)}:null}),[ticket.accountId,ticket.instrument,ticket.side,ticket.orderType,ticket.quantity,ticket.stopLoss,ticket.takeProfit])
  useEffect(()=>{
    if(!payload.account_id||!payload.instrument_id||ticket.preview)return
    const controller=new AbortController();const current=++sequence.current;let timer:ReturnType<typeof setTimeout>;let stopped=false
    const run=async()=>{if(stopped)return;if(document.hidden){timer=setTimeout(run,15000);return}setLoading(true)
      try{const result=await browserAfdFetch<Calculation>("trading/order-calculations",{method:"POST",body:JSON.stringify(payload),signal:controller.signal});if(current===sequence.current)setTicket(value=>value.preview?value:{...value,calculation:result}) ;if(current===sequence.current)setError("")}
      catch(cause){if(!controller.signal.aborted&&current===sequence.current)setError(cause instanceof BrowserAfdError&&cause.status===404?"Order calculations are not available for this account or instrument.":cause instanceof Error?cause.message:"Order calculations are unavailable.")}
      finally{if(current===sequence.current)setLoading(false);if(!stopped)timer=setTimeout(run,5000)}}
    timer=setTimeout(run,350);return()=>{stopped=true;clearTimeout(timer);controller.abort()}
  },[payload,ticket.preview])
  const update=(change:Partial<Ticket>)=>setTicket(current=>({...current,...change,preview:null}))
  const chooseInstrument=(instrument:Instrument)=>{update({instrument:instrument.canonical_id,calculation:null});setSymbolQuery(instrument.display_symbol);setSymbolResults([]);setSymbolSearched(false)}
  const calculation=activeCalculation(ticket.calculation,ticket.preview);const entry=entryForSide(ticket.side,calculation?.quote??null)
  const localStop=ticket.stopLoss.mode==="price"&&ticket.stopLoss.value?Number(ticket.stopLoss.value):calculation?.stop_loss?.price??null
  const localTarget=ticket.takeProfit.mode==="price"&&ticket.takeProfit.value?Number(ticket.takeProfit.value):calculation?.take_profit?.price??null
  const stopError=protectionMessage("Stop Loss",ticket.side,localStop,entry);const targetError=protectionMessage("Take Profit",ticket.side,localTarget,entry)
  const unit=calculation?.quantity.unit==="lot"?"Lots":"Contracts";const step=calculation?.quantity.step??.01;const minimum=calculation?.quantity.minimum??.01
  const expired=previewExpired(ticket.preview)
  return <div className="space-y-5"><CapabilityNotice live={live} calculation={calculation} error={error}/><ol className="grid grid-cols-5 gap-2 text-center text-xs">{stages.map((stage,index)=><li className={`rounded border p-2 ${index===0?"bg-accent font-semibold":"text-muted-foreground"}`} key={stage}>{stage}</li>)}</ol><Tabs defaultValue="ticket"><TabsList className="grid w-full grid-cols-4"><TabsTrigger value="ticket">Order Ticket</TabsTrigger><TabsTrigger value="positions">Open Positions</TabsTrigger><TabsTrigger value="pending">Pending Orders</TabsTrigger><TabsTrigger value="history">Order History</TabsTrigger></TabsList><TabsContent value="ticket"><div className="grid gap-5 xl:grid-cols-[1fr_.8fr]"><Card><CardHeader><CardTitle>Build Order</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">
    <div><Label htmlFor="trade-symbol">Symbol</Label><div className="relative mt-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input id="trade-symbol" value={symbolQuery} onChange={event=>setSymbolQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&symbolResults[0]){event.preventDefault();chooseInstrument(symbolResults[0])}if(event.key==="Escape")setSymbolResults([])}} placeholder="Search symbols or descriptions" className="pl-9 pr-9" role="combobox" aria-expanded={Boolean(symbolResults.length)} aria-controls="trade-symbol-results"/>{symbolQuery&&<button type="button" onClick={()=>{setSymbolQuery("");setSymbolResults([])}} aria-label="Clear symbol search" className="absolute right-3 top-3"><X className="h-4 w-4"/></button>}{(symbolSearching||symbolResults.length>0||symbolSearched)&&<div id="trade-symbol-results" role="listbox" className="absolute z-30 mt-1 max-h-64 w-full overflow-y-auto rounded border bg-popover shadow-lg">{symbolSearching?<p className="p-3 text-sm">Searching…</p>:symbolResults.map(instrument=><button type="button" role="option" key={instrument.canonical_id} className="block w-full border-b p-3 text-left hover:bg-accent" onClick={()=>chooseInstrument(instrument)}><strong>{instrument.display_symbol}</strong><span className="block text-xs text-muted-foreground">{instrument.description} · {instrument.asset_class}{instrument.exchange?` · ${instrument.exchange}`:""}</span></button>)}{symbolSearched&&!symbolResults.length&&<p className="p-3 text-sm text-muted-foreground">No matching instruments.</p>}</div>}</div>{ticket.instrument&&<p className="mt-1 text-xs text-muted-foreground">Selected: {ticket.instrument}</p>}</div>
    <div><Label>Side</Label><div className="grid grid-cols-2 gap-2" role="group" aria-label="Order side">{(["buy","sell"] as Side[]).map(side=><Button key={side} type="button" variant={ticket.side===side?"default":"outline"} aria-pressed={ticket.side===side} onClick={()=>update({side,calculation:null})}>{ticket.side===side&&<Check aria-hidden="true"/>}{side==="buy"?"Buy":"Sell"}{ticket.side===side&&<span className="sr-only"> selected</span>}</Button>)}</div></div>
    <div><Label htmlFor="order-type">Order type</Label><select id="order-type" className="h-10 w-full rounded border bg-background px-3" value={ticket.orderType} onChange={event=>update({orderType:event.target.value as Ticket["orderType"],calculation:null})}><option value="market">Market</option><option value="limit">Limit</option><option value="stop">Stop</option></select></div>
    <div><Label htmlFor="quantity">Quantity</Label><div className="flex items-center gap-2"><Button type="button" size="icon" variant="outline" aria-label="Decrease quantity" onClick={()=>update({quantity:stepQuantity(ticket.quantity,-1,step,minimum,calculation?.quantity.maximum),calculation:null})}><Minus/></Button><Input id="quantity" inputMode="decimal" type="number" min={minimum} max={calculation?.quantity.maximum??undefined} step={step} value={ticket.quantity} onChange={event=>update({quantity:Number(event.target.value),calculation:null})}/><Button type="button" size="icon" variant="outline" aria-label="Increase quantity" onClick={()=>update({quantity:stepQuantity(ticket.quantity,1,step,minimum,calculation?.quantity.maximum),calculation:null})}><Plus/></Button><span className="text-sm font-medium">{unit}</span></div><QuantityContext calculation={calculation}/></div>
    <ProtectionField label="Stop Loss" modes={["price","pips"]} value={ticket.stopLoss} precision={calculation?.price_precision} calculation={calculation?.stop_loss} error={stopError} onChange={stopLoss=>update({stopLoss:stopLoss as Protection,calculation:null})}/>
    <ProtectionField label="Take Profit" modes={["price","pips","reward_multiple"]} value={ticket.takeProfit} precision={calculation?.price_precision} calculation={calculation?.take_profit} error={ticket.takeProfit.mode==="reward_multiple"&&!calculation?.stop_loss?.distance_pips?"Define a valid Stop Loss before using an R:R target.":targetError} onChange={takeProfit=>update({takeProfit:takeProfit as Target,calculation:null})}/>
    {expired&&<p className="sm:col-span-2 text-sm text-amber-600">The order preview expired. Return to Edit and refresh the preview before submitting.</p>}
    <div className="sm:col-span-2 rounded-lg border bg-muted/30 p-4">{calculation?.capabilities.preview?<Button className="w-full" disabled={Boolean(calculation.blocking_reasons.length)||expired}>Continue to Order Preview</Button>:<div><p className="font-medium">{calculation?.entry_price!=null?"Order estimate ready":"Building order estimate"}</p><p className="mt-1 text-sm text-muted-foreground">Pricing, sizing, exposure, and protection levels are available. Broker preview and submission will activate here when those backend capabilities are enabled.</p></div>}</div>
  </CardContent></Card><ReviewPanel ticket={ticket} calculation={calculation} selected={selected} live={live} loading={loading}/></div></TabsContent>{["positions","pending","history"].map(tab=><TabsContent value={tab} key={tab}><Card><CardContent className="p-10 text-center text-sm text-muted-foreground">{tab==="positions"?"Open positions will appear here when the authenticated positions endpoint is enabled.":tab==="pending"?"Pending orders will appear here when the backend order ledger is enabled.":"Order history will appear here after submitted orders are reconciled with the broker."}</CardContent></Card></TabsContent>)}</Tabs></div>
}

function CapabilityNotice({live,calculation,error}:{live:boolean;calculation:Calculation|null;error:string}){const text=error||(!calculation?"Select an account to load broker-backed pricing and calculations.":calculation.capabilities.preview?calculation.capabilities.submission?"Broker preview and submission are available.":"Broker preview is available; submission remains locked.":"Broker pricing and order estimates are connected. Preview and submission are not yet enabled for this provider.");return <div className={`flex gap-3 rounded-xl border p-4 text-sm ${error||live?"border-amber-500/30 bg-amber-500/10":"border-emerald-500/30 bg-emerald-500/10"}`}><AlertTriangle className="h-5 w-5"/><strong>{text}</strong></div>}
function QuantityContext({calculation}:{calculation:Calculation|null}){if(!calculation)return null;const values=[calculation.pip_value&&`Pip value: ${money(calculation.pip_value.value,calculation.pip_value.currency)} per pip`,calculation.notional_exposure!=null&&`Estimated exposure: ${money(calculation.notional_exposure,calculation.pip_value?.currency)}`,calculation.margin_estimate!=null&&`Estimated margin: ${money(calculation.margin_estimate,calculation.pip_value?.currency)}`].filter(Boolean);return values.length?<p className="mt-1 text-xs text-muted-foreground">{values.join(" · ")}</p>:<p className="mt-1 text-xs text-muted-foreground">Monetary sizing is unavailable because the provider cannot verify conversion or margin data.</p>}
function ProtectionField({label,modes,value,precision,calculation,error,onChange}:{label:"Stop Loss"|"Take Profit";modes:Array<ProtectionMode|TargetMode>;value:Protection|Target;precision?:number;calculation:Calculation["stop_loss"]|Calculation["take_profit"]|undefined;error:string|null;onChange:(value:Protection|Target)=>void}){return <div><div className="flex items-center justify-between"><Label htmlFor={label}>{label}</Label><div className="flex gap-1">{modes.map(mode=><Button key={mode} type="button" size="sm" variant={value.mode===mode?"secondary":"ghost"} aria-pressed={value.mode===mode} onClick={()=>onChange({...value,mode})}>{mode==="price"?"Price":mode==="pips"?"Pips":"R:R"}</Button>)}</div></div><Input id={label} inputMode="decimal" type="number" step="any" value={value.value} onChange={event=>onChange({...value,value:event.target.value})} placeholder={value.mode==="price"?`Price${precision!=null?` (${precision} decimals)`:""}`:value.mode==="pips"?"Pip distance":"Reward multiple"}/>{error?<p role="alert" className="mt-1 text-xs text-red-600">{error}</p>:calculation&&<p className="mt-1 text-xs text-muted-foreground">{value.mode!=="price"&&calculation.price!=null?`Derived price: ${calculation.price} · `:""}{calculation.distance_pips!=null?`${calculation.distance_pips} pips · `:""}{"estimated_loss" in calculation&&calculation.estimated_loss!=null?`Estimated loss: -${money(calculation.estimated_loss)} · ${calculation.risk_percent??"—"}% risk`:"estimated_profit" in calculation&&calculation.estimated_profit!=null?`Estimated profit: +${money(calculation.estimated_profit)} · ${calculation.reward_to_risk??"—"}R`:""}</p>}</div>}
function ReviewPanel({ticket,calculation,selected,live,loading}:{ticket:Ticket;calculation:Calculation|null;selected:ReturnType<typeof useAccountContext>["selected"];live:boolean;loading:boolean}){const enough=selected&&calculation?.entry_price!=null&&ticket.quantity>0;return <Card><CardHeader><div className="flex justify-between"><CardTitle>Order Estimate</CardTitle>{selected&&<Badge variant={live?"destructive":"secondary"}>{selected.environment.toUpperCase()}</Badge>}</div></CardHeader><CardContent className="space-y-3">{!enough?<p className="text-sm text-muted-foreground">Select a symbol, side, and quantity to calculate the order.{loading?" Updating…":""}</p>:<><Datum label="Trading Account" value={`${selected.accountNumber} · ${selected.broker} · ${selected.environment}`}/><Datum label="Order" value={`${ticket.side==="buy"?"Buy":"Sell"} ${ticket.quantity.toFixed(2)} ${calculation.quantity.unit==="lot"?"Lots":"Contracts"} ${ticket.instrument.split(":").at(-1)}`}/><Datum label="Estimated Entry" value={`${calculation.entry_price} ${calculation.entry_side}`}/>{calculation.pip_value&&<Datum label="Pip Value" value={`${money(calculation.pip_value.value,calculation.pip_value.currency)} per pip`}/>} {calculation.stop_loss?.price!=null&&<Datum label="Stop Loss" value={`${calculation.stop_loss.price}${calculation.stop_loss.distance_pips!=null?` · ${calculation.stop_loss.distance_pips} pips`:""}${calculation.stop_loss.estimated_loss!=null?` · -${money(calculation.stop_loss.estimated_loss,calculation.pip_value?.currency)}`:""}`}/>} {calculation.take_profit?.price!=null&&<Datum label="Take Profit" value={`${calculation.take_profit.price}${calculation.take_profit.distance_pips!=null?` · ${calculation.take_profit.distance_pips} pips`:""}${calculation.take_profit.estimated_profit!=null?` · +${money(calculation.take_profit.estimated_profit,calculation.pip_value?.currency)}`:""}`}/>} {calculation.take_profit?.reward_to_risk!=null&&<Datum label="Reward-to-Risk" value={`${calculation.take_profit.reward_to_risk}R`}/>} {calculation.margin_estimate!=null&&<Datum label="Estimated Margin" value={money(calculation.margin_estimate,calculation.pip_value?.currency)}/>}<p className="text-xs text-muted-foreground">Bid {calculation.quote.bid} · Ask {calculation.quote.ask} · Spread {calculation.quote.spread} · {calculation.quote.source} · {calculation.quote.stale?"Stale":"Fresh"}{calculation.quote.timestamp?` · ${new Date(calculation.quote.timestamp).toLocaleTimeString()}`:""}</p></>}</CardContent></Card>}
function money(value:number,currency?:string|null){try{return new Intl.NumberFormat(undefined,{style:"currency",currency:currency||"USD",maximumFractionDigits:2}).format(value)}catch{return `${value.toFixed(2)} ${currency||""}`}}
function Datum({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 border-b pb-2 text-sm"><span className="text-muted-foreground">{label}</span><strong className="text-right">{value}</strong></div>}