"use client"
import { useState } from "react"
import { useTheme } from "next-themes"
import type { UserPreferences } from "@/lib/afd/contracts"
import { mutateAfd } from "@/lib/afd/browser-client"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
const notificationLabels:Record<string,string>={demo_trade_submitted:"Demo trade submitted",trade_rejected:"Trade rejected",strategy_blocked:"Strategy blocked",daily_loss_limit_reached:"Daily loss limit reached",trading_connection_disconnected:"Trading connection disconnected",schedule_failed:"Schedule failed",automation_interruption:"Automation interruption",daily_summary:"Daily summary"}
export function NotificationSettings({initial}:{initial:UserPreferences}){const [value,setValue]=useState(initial);const [status,setStatus]=useState("");async function save(){setStatus("Saving…");try{setValue(await mutateAfd<UserPreferences>("user-preferences","PATCH",{notifications:value.notifications}));setStatus("Preferences confirmed.")}catch{setStatus("Save failed. Preferences were not changed.")}}return <Card><CardHeader><CardTitle>In-app notifications</CardTitle><p className="text-sm text-muted-foreground">Email is not offered because no delivery service is configured.</p></CardHeader><CardContent className="space-y-3">{Object.entries(notificationLabels).map(([key,label])=><label className="flex items-center justify-between rounded border p-3" key={key}><span>{label}</span><Switch checked={Boolean(value.notifications[key])} onCheckedChange={checked=>setValue(current=>({...current,notifications:{...current.notifications,[key]:checked}}))}/></label>)}<p role="status" className="text-sm">{status}</p><Button onClick={()=>void save()}>Save notification preferences</Button></CardContent></Card>}
export function AppearanceSettings({initial}:{initial:UserPreferences}){const {setTheme}=useTheme();const [appearance,setAppearance]=useState(initial.appearance);const [status,setStatus]=useState("");async function save(){setStatus("Saving…");try{await mutateAfd("user-preferences","PATCH",{appearance});setTheme(appearance);setStatus("Appearance confirmed.")}catch{setStatus("Save failed.")}}return <Card><CardHeader><CardTitle>Appearance</CardTitle></CardHeader><CardContent><div className="grid grid-cols-3 gap-2">{["light","dark","system"].map(value=><Button key={value} variant={appearance===value?"default":"outline"} onClick={()=>setAppearance(value as UserPreferences["appearance"])}>{value[0].toUpperCase()+value.slice(1)}</Button>)}</div><p className="my-3 text-sm">{status}</p><Button onClick={()=>void save()}>Save appearance</Button></CardContent></Card>}
export function RegionalSettings({initial}:{initial:UserPreferences}){const [value,setValue]=useState(initial);const [status,setStatus]=useState("");async function save(){setStatus("Saving…");try{setValue(await mutateAfd<UserPreferences>("user-preferences","PATCH",value));setStatus("Regional settings confirmed.")}catch{setStatus("Save failed.")}}return <Card><CardHeader><CardTitle>Timezone and formats</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="Timezone"><input className="h-10 w-full rounded border bg-background px-3" value={value.timezone} onChange={event=>setValue(current=>({...current,timezone:event.target.value}))}/></Field><Choice label="Date format" value={value.date_format} values={["locale","month_day_year","day_month_year","year_month_day"]} onChange={date_format=>setValue(current=>({...current,date_format}))}/><Choice label="Time format" value={value.time_format} values={["locale","12_hour","24_hour"]} onChange={time_format=>setValue(current=>({...current,time_format}))}/><Choice label="Currency display" value={value.currency_display} values={["account","usd"]} onChange={currency_display=>setValue(current=>({...current,currency_display}))}/><p role="status" className="text-sm">{status}</p><Button onClick={()=>void save()}>Save regional settings</Button></CardContent></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><Label>{label}</Label>{children}</div>}
function Choice({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(value:string)=>void}){return <Field label={label}><select value={value} onChange={event=>onChange(event.target.value)} className="h-10 w-full rounded border bg-background px-3">{values.map(item=><option value={item} key={item}>{item.replaceAll("_"," ")}</option>)}</select></Field>}
