export type Environment = "demo" | "live" | string
export type Outcome = "TRADE" | "NO_TRADE" | "BLOCKED" | "MARKET_CLOSED" | "SKIPPED" | "ERROR"

export interface BrokerStatus { status: string; connected: boolean; message?: string; retryable?: boolean; selected_account?: { account_id: string; account_number: string; account_alias?: string; server: string; environment?: Environment } }
export interface Connection { public_id: string; label?: string; display_name?:string; provider_type?:string; roles?:string[]; broker_name?: string; platform_name?: string; server: string; environment: Environment; enabled: boolean; account_count: number; last_verified_at?: string; is_default: boolean }
export interface ProviderCapabilities { asset_classes:string[]; supported_order_types:string[]; account_snapshot:boolean; positions:boolean; pending_orders:boolean; order_preview:boolean; order_submission:boolean; cancellation:boolean; partial_close:boolean; trailing_stop:boolean; paper_or_demo:boolean; live:boolean; autonomous_demo:boolean; autonomous_live:boolean; market_data:boolean; fractional_quantity:boolean; options:boolean; extended_hours:boolean }
export interface ProviderDescriptor { provider_type:string; display_name:string; category:string; roles:string[]; broker_name?:string|null; platform_name?:string|null; status:string; execution_provider:boolean; capabilities:ProviderCapabilities }
export interface CanonicalInstrument { canonical_id:string; symbol:string; display_symbol:string; description:string; asset_class:string; exchange?:string; provider_symbols:Record<string,string> }
export interface MarketSummary { instrument:CanonicalInstrument; quote:{price:number|null;change:number|null;change_percent:number|null;open:number|null;high:number|null;low:number|null;previous_close:number|null;bid?:number|null;ask?:number|null;timestamp:string|null;source?:string;authoritative_for_execution?:boolean}|null; market_status:{state:string;label:string}; drivers:Array<{series_id:string;label:string;value:number;unit?:string;observation_date:string;source:string;category:string;applies_to:string;stale:boolean}>; tradability?:{available:boolean;currently_tradable:boolean}|null; sources:Array<{provider:string;status:string;updated_at?:string;message?:string}>; partial:boolean }
export interface ProfileSummary { public_id: string; name: string; account_id: string; account_alias: string; account_number?:string; broker_name?:string; account_environment?:string; execution_mode: string; enabled: boolean; strategy_name?: string; profile_v2?:ExecutionProfileV2; provider_readiness?: { ready?: boolean; reason?: string } }
export interface Account { public_id: string; account_number?: string; account_alias: string; nickname?: string; account_name?: string; provider_type?:string; asset_classes?:string[]; capabilities?:ProviderCapabilities; broker_name?: string; platform_name?: string; currency?: string; environment: Environment; is_demo?: number | boolean | null; available: boolean; locally_enabled: boolean; is_default_analysis: boolean; is_primary?:boolean; last_verified_at?:string; connection_id: string; profiles: ProfileSummary[] }
export interface AutonomousControls { global_autonomous_kill_switch: boolean; demo_autonomous_enabled: boolean; live_autonomous_enabled: boolean; live_execution_supported: boolean; live_confirmation_phrase?: string; updated_at: string; effective: { demo: string; live: string } }
export interface AutonomousRun { run_id: string; outcome?: Outcome; status?: string; started_at?: string; completed_at?: string; profile_ref?: string; account_alias?: string; chosen_instrument?: string; reason_codes?: string[]; dry_run?:boolean; trigger_reason?:string }
export interface UserPreferences { appearance:"light"|"dark"|"system"; timezone:string; date_format:string; time_format:string; currency_display:string; notifications:Record<string,boolean>; updated_at:string }
export interface WatchlistItem { symbol:string; canonical_id?:string; position:number; pinned:boolean }
export interface Watchlist { id:string; name:string; is_default:boolean; items:WatchlistItem[]; updated_at:string }
export interface ActivityEvent { id:string; event_type:string; occurred_at:string; account_alias?:string; account_number?:string; environment?:string; profile_id?:string; strategy_name?:string; outcome?:string; symbol?:string; reason_codes?:string[]; confidence?:number; dry_run?:boolean; run_id?:string }
export interface DemoExecution { id: string; action_type?: string; state?: string; created_at?: string; symbol?: string; result?: string }
export interface Schedule { id: string; profile_ref: string; timezone: string; schedule_type?: string; recurrence?: { type: string; times: string[]; days?: string[]; sessions?: string[]; start_time?: string; end_time?: string; interval_minutes?: number; market_aware?:boolean }; expression: { times: string[] }; enabled: boolean; next_run_times?: string[]; readiness_warnings?:Array<{code:string;message:string}>; next_run_at?: string; next_run_at_local?: string; last_run_at?: string; last_run_at_local?: string; last_run_status?: string; maximum_lateness_seconds: number; latest_dispatch?: { id: string; state: string; safe_retry: boolean; reason_code?: string; outcome?: string } }
export interface WorkerHealth { status: string; workers: Array<{ worker_id: string; status: string; last_heartbeat_at: string; healthy: boolean }> }
export interface DailySummary { date: string; outcomes: Record<Outcome, number>; daily_entry_count: number; kill_switch: boolean; armed_profiles: number }
export interface Instrument { instrument_id: string; broker_symbol: string; description?: string; asset_class: string; market_group: string; currently_tradable: boolean }
export interface MarketGroup { id: string; instrument_count: number }

export interface TradingPolicy { mode: "adaptive" | "preset"; preset_id: "hourly_forex" | null; decision_interval: "scheduled"; minimum_confidence: number }
export interface MarketUniverse { mode: "all_available" | "groups" | "custom"; groups: string[]; included_instrument_ids: string[]; excluded_instrument_ids: string[] }
export interface RiskPolicy { mode: "fixed" | "adaptive"; fixed_risk_pct: number; base_risk_pct: number; minimum_risk_pct: number; maximum_risk_pct: number; maximum_total_open_risk_pct: number; maximum_margin_utilization_pct: number | null; maximum_correlated_risk_pct: number | null; daily_loss_limit_pct: number; drawdown_cutoff_pct: number; maximum_open_positions: number; maximum_pending_entry_orders: number; maximum_new_entries_per_day: number }
export interface CapitalAllocation { mode: "full_account" | "fixed_amount" | "equity_percentage"; fixed_amount: number | null; equity_percentage: number | null; risk_base: "account_equity" | "allocated_capital"; compounding_mode: "disabled" | "realized_pnl" | "periodic_rebalance"; maximum_margin_utilization_pct: number; maximum_gross_exposure_multiple: number | null; allow_shared_capital: boolean }
export interface ExitPolicy { stop_loss: { enabled: boolean; mode: string; fixed_distance: number | null; fixed_percentage: number | null; maximum_risk_distance: number | null }; take_profit: { enabled: boolean; mode: string; minimum_reward_to_risk: number; target_reward_to_risk: number }; trailing_stop: { enabled: boolean; activation_mode: string; activation_value: number | null; trail_value: number | null }; break_even: { enabled: boolean; activation_reward_multiple: number; offset: number }; partial_exits: Array<Record<string, unknown>> }
/** @deprecated Schedules are managed by the structured schedule builder, not the profile editor. */
export interface SchedulePolicy { timezone: string; times: string[]; market_aware: boolean; run_when_any_selected_market_is_open: boolean }
export interface ExecutionProfileV2 { schema_version: 2; asset_class?:"forex"|"equities"|"options"; trading_account?:string|null; provider_capability_requirements?:string[]; forex?:Record<string,unknown>|null; equities?:Record<string,unknown>|null; options?:Record<string,unknown>|null; trading_policy: TradingPolicy; market_universe: MarketUniverse; risk_policy: RiskPolicy; capital_allocation: CapitalAllocation; exit_policy: ExitPolicy; schedule_policy: SchedulePolicy; enabled: boolean }
export interface ProfileContract { profile_id: string; name?:string; account_id: string; account_alias: string; account_number?: string; broker_name?: string; account_environment?: string; nickname?: string; profile: ExecutionProfileV2; supported_enum_options: Record<string, unknown>; server_defaults: ExecutionProfileV2; field_validation_ranges: Record<string, { minimum?: number; exclusive_minimum?: number; maximum?: number }>; account_capabilities: { partial_exit_capability?: { execution_supported: boolean }; live_demo_restrictions?: { live_autonomous_execution: boolean }; [key: string]: unknown }; available_market_groups: string[]; warnings: Array<{ code: string; message: string }>; migration: { state: string; legacy_compatibility: boolean } }
export interface RunAudit { run_id: string; outcome: string; selected_market_universe: string[]; markets_currently_open: string[]; candidates_screened: number; candidates_deeply_analyzed: number; chosen_instrument?: string; reason_codes: string[]; risk_state_counts: Record<string, unknown>; execution_result: Record<string, unknown>; usage: Record<string, unknown> }
