"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { mutateAfd, BrowserAfdError } from "@/lib/afd/browser-client"

function value(row: Record<string, unknown>, ...keys: string[]) { for (const key of keys) if (row[key] != null) return String(row[key]); return "" }
export function AccountSelector({ accounts, connectionId, initialError }: { accounts: Array<Record<string, unknown>>; connectionId?: string; initialError: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(""); const [error, setError] = useState(initialError)
  async function select(row: Record<string, unknown>) { const id = value(row, "accountId", "account_id"); setBusy(id); setError(""); try { await mutateAfd("broker/tradelocker/select-account", "POST", { account_id: id, account_number: value(row, "accNum", "accountNumber", "account_number"), connection_id: connectionId }); router.replace("/dashboard?connected=1") } catch (caught) { setError(caught instanceof BrowserAfdError ? caught.message : "The account could not be selected.") } finally { setBusy("") } }
  return <section className="w-full max-w-2xl rounded-2xl border bg-card p-6 shadow-sm sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-600">Broker onboarding</p><h1 className="mt-2 text-2xl font-semibold">Select your default account</h1><p className="mt-2 text-sm text-muted-foreground">This sets the backend account context. You can change it later in account settings.</p>{error && <p role="alert" className="mt-5 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 space-y-3">{accounts.map((row, index) => { const id = value(row, "accountId", "account_id"); const number = value(row, "accNum", "accountNumber", "account_number"); return <button key={`${id}-${number}-${index}`} disabled={Boolean(busy)} onClick={() => select(row)} className="flex w-full items-center justify-between rounded-xl border p-4 text-left hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span><strong className="block">{value(row, "name", "accountName") || `Account ${number}`}</strong><span className="text-sm text-muted-foreground">{number} · {value(row, "currency") || "Currency unavailable"}</span></span><span className="text-sm font-medium text-emerald-600">{busy === id ? "Selecting…" : "Select"}</span></button> })}{!accounts.length && !error && <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">No accounts were returned by TradeLocker.</p>}</div><Button variant="ghost" className="mt-5" onClick={() => router.push("/connect-tradelocker")}>Back to connection</Button></section>
}
