"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { mutateAfd, BrowserAfdError } from "@/lib/afd/browser-client"
import { normalizeDiscoveredAccounts, type DiscoveredAccount } from "@/lib/afd/onboarding"
import { StatusPill } from "@/components/desk/status-pill"

export function AccountSelector({ accounts, connectionId, initialError }: { accounts: Array<Record<string, unknown>>; connectionId?: string; initialError: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(""); const [error, setError] = useState(initialError)
  const discovered = normalizeDiscoveredAccounts(accounts)
  async function select(account: DiscoveredAccount) { setBusy(account.accountId); setError(""); try { await mutateAfd("broker/tradelocker/select-account", "POST", { account_id: account.accountId, account_number: account.accountNumber, connection_id: connectionId }); router.replace("/dashboard?connected=1") } catch (caught) { setError(caught instanceof BrowserAfdError ? caught.message : "The account could not be selected.") } finally { setBusy("") } }
  return <section className="w-full max-w-3xl rounded-2xl border bg-card p-6 shadow-sm sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-600">Broker onboarding</p><h1 className="mt-2 text-2xl font-semibold">Select your default account</h1><p className="mt-2 text-sm text-muted-foreground">All discovered accounts remain stored. Choose the one the desk should use when no account is specified.</p>{error && <p role="alert" className="mt-5 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 space-y-3">{discovered.map((account) => <article key={`${account.accountId}-${account.accountNumber}`} className="flex flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong>{account.name}</strong><StatusPill label={account.environment.toUpperCase()} tone={account.environment === "live" ? "bad" : account.environment === "demo" ? "good" : "neutral"} /><StatusPill label={account.available ? "Available" : "Unavailable"} tone={account.available ? "good" : "warn"} /></div><dl className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-sm text-muted-foreground"><div><dt className="inline">Account </dt><dd className="inline font-medium text-foreground">{account.accountNumber}</dd></div><div><dt className="inline">Currency </dt><dd className="inline font-medium text-foreground">{account.currency}</dd></div></dl></div><Button disabled={Boolean(busy) || !account.available} onClick={() => select(account)}>{busy === account.accountId ? "Selecting…" : "Select as default"}</Button></article>)}{!discovered.length && !error && <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">No accounts were returned by TradeLocker.</p>}</div><Button variant="ghost" className="mt-5" onClick={() => router.push("/connect-tradelocker")}>Back to connection</Button></section>
}
