"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { mutateAfd,BrowserAfdError } from "@/lib/afd/browser-client"
import { normalizeDiscoveredAccounts,type DiscoveredAccount } from "@/lib/afd/onboarding"
import { formatEnum } from "@/lib/afd/display"
import { StatusPill } from "@/components/desk/status-pill"
export function AccountSelector({accounts,connectionId,initialError}:{accounts:Array<Record<string,unknown>>;connectionId?:string;initialError:string}){const router=useRouter();const [busy,setBusy]=useState("");const [error,setError]=useState(initialError);const discovered=normalizeDiscoveredAccounts(accounts);async function select(account:DiscoveredAccount){setBusy(account.accountId);setError("");try{await mutateAfd("broker/tradelocker/select-account","POST",{account_id:account.accountId,account_number:account.accountNumber,connection_id:connectionId});router.replace("/dashboard?connected=1")}catch(e){setError(e instanceof BrowserAfdError?e.message:"The account could not be selected.")}finally{setBusy("")}}return <section className="w-full max-w-3xl rounded-2xl border bg-card p-6 sm:p-8"><p className="text-xs font-semibold uppercase text-emerald-600">Trading account onboarding</p><h1 className="mt-2 text-2xl font-semibold">Select your primary account</h1><p className="mt-2 text-sm text-muted-foreground">Every discovered account remains stored. Nothing is selected automatically.</p>{error&&<p role="alert" className="mt-5 rounded border border-red-500/30 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 space-y-3">{discovered.map(account=><article key={`${account.accountId}-${account.accountNumber}`} className="flex flex-col justify-between gap-4 rounded-xl border p-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><strong>{account.accountNumber}</strong><StatusPill label={account.available?"Available":"Unavailable"} tone={account.available?"good":"warn"}/></div><p className="mt-1 text-sm text-muted-foreground">{account.brokerName} · {formatEnum(account.environment)}{account.name&&!account.name.startsWith("Account ")?` · ${account.name}`:""}</p><p className="text-xs text-muted-foreground">Currency: {account.currency}</p></div><Button disabled={Boolean(busy)||!account.available} onClick={()=>void select(account)}>{busy===account.accountId?"Selecting…":"Select"}</Button></article>)}{!discovered.length&&!error&&<p className="rounded border border-dashed p-6 text-center text-sm">No accounts were returned by TradeLocker.</p>}</div><Button variant="ghost" className="mt-5" onClick={()=>router.push("/connect-tradelocker")}>Back to connection</Button></section>}
