"use client"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { FormEvent, useState } from "react"
import { AlertTriangle, Plus, ShieldAlert } from "lucide-react"
import type { Account, AutonomousControls, AutonomousRun, ProfileSummary, Schedule } from "@/lib/afd/contracts"
import { BrowserAfdError, browserAfdFetch, mutateAfd } from "@/lib/afd/browser-client"
import { updateControlsWithRollback } from "@/lib/afd/autonomous"
import { StatusPill } from "@/components/desk/status-pill"
import { EmptyState } from "@/components/desk/page-header"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"

const LIVE_PHRASE = "ENABLE LIVE AUTONOMY"
export function AutonomousWorkspace({ initialControls, accounts, profiles, schedules, runs, degraded }: { initialControls: AutonomousControls; accounts: Account[]; profiles: ProfileSummary[]; schedules: Schedule[]; runs: AutonomousRun[]; degraded: boolean }) {
  const router = useRouter(); const [controls, setControls] = useState(initialControls); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [profileStatus, setProfileStatus] = useState<Record<string, string>>({}); const [livePhrase, setLivePhrase] = useState(""); const [liveOpen, setLiveOpen] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [deleteProfile, setDeleteProfile] = useState<ProfileSummary | null>(null); const [confirmation, setConfirmation] = useState("")
  async function patch(patchValue: object) { const previous = controls; setBusy("controls"); setError(""); try { await updateControlsWithRollback(previous, patchValue, setControls, mutateAfd<AutonomousControls>); router.refresh() } catch (caught) { setError(caught instanceof BrowserAfdError ? caught.message : "Backend confirmation failed. The previous safety state was restored.") } finally { setBusy("") } }
  async function toggleProfile(profile: ProfileSummary, enabled: boolean) { setBusy(profile.public_id); try { await mutateAfd(`execution-profiles/${profile.public_id}`, "PATCH", { enabled }); router.refresh() } catch (caught) { setError(caught instanceof BrowserAfdError ? caught.message : "Profile state was not changed.") } finally { setBusy("") } }
  async function verifyProfile(profile: ProfileSummary) { setBusy(`status-${profile.public_id}`); try { const result = await browserAfdFetch<{ autonomous_active?: boolean; blocking_reasons?: unknown[] }>(`execution-profiles/${profile.public_id}/autonomy/status`); const reasons = Array.isArray(result.blocking_reasons) ? result.blocking_reasons.map(String) : []; setProfileStatus((current) => ({ ...current, [profile.public_id]: result.autonomous_active ? "Autonomous active" : reasons.length ? `Blocked: ${reasons.join(", ")}` : "Manual / eligible" })) } catch { setProfileStatus((current) => ({ ...current, [profile.public_id]: "Status unavailable" })) } finally { setBusy("") } }
  async function remove() { if (!deleteProfile || confirmation !== deleteProfile.name) return; setBusy(deleteProfile.public_id); try { await browserAfdFetch(`execution-profiles/${deleteProfile.public_id}?confirmation_name=${encodeURIComponent(confirmation)}`, { method: "DELETE" }); setDeleteProfile(null); setConfirmation(""); router.refresh() } catch (caught) { setError(caught instanceof BrowserAfdError ? caught.message : "Profile was not deleted.") } finally { setBusy("") } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy("create"); try { await mutateAfd("execution-profiles", "POST", { name: data.get("name"), account_id: data.get("account_id"), execution_mode: "read_only" }); setCreateOpen(false); router.refresh() } catch (caught) { setError(caught instanceof BrowserAfdError ? caught.message : "Profile was not created.") } finally { setBusy("") } }
  return <div className="space-y-6">{(degraded || error) && <div role="alert" className="flex gap-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm"><AlertTriangle className="h-5 w-5 shrink-0" /><span>{error || "Some backend sections are degraded. Unknown safety state remains blocked."}</span></div>}<Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2"><ShieldAlert className="h-5 w-5" /> Global safety controls</CardTitle><StatusPill label={controls.global_autonomous_kill_switch ? "Trading blocked" : "Kill switch off"} tone={controls.global_autonomous_kill_switch ? "warn" : "bad"} /></div></CardHeader><CardContent className="divide-y"> <Control title="Global kill switch" detail="Blocks all new autonomous demo and live submissions." checked={controls.global_autonomous_kill_switch} disabled={Boolean(busy)} onChange={(value) => patch({ global_autonomous_kill_switch: value })} /><Control title="Demo autonomous trading" detail={`Effective backend state: ${controls.effective.demo}`} checked={controls.demo_autonomous_enabled} disabled={Boolean(busy) || controls.global_autonomous_kill_switch} onChange={(value) => patch({ demo_autonomous_enabled: value })} /><Control title="Live autonomous trading" detail={controls.live_execution_supported ? `Effective backend state: ${controls.effective.live}` : "This backend explicitly reports live autonomous execution as unsupported."} checked={controls.live_autonomous_enabled} disabled={Boolean(busy) || controls.global_autonomous_kill_switch || !controls.live_execution_supported} onChange={(value) => value ? setLiveOpen(true) : patch({ live_autonomous_enabled: false })} /></CardContent></Card>
    <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-semibold">Execution profiles</h2><p className="text-sm text-muted-foreground">Grouped by backend account context.</p></div><Button onClick={() => setCreateOpen(true)} disabled={!accounts.length}><Plus className="mr-2 h-4 w-4" /> Create profile</Button></div><div className="space-y-5">{accounts.map((account) => { const owned = profiles.filter((profile) => profile.account_alias === account.account_alias); return <Card key={account.public_id}><CardHeader><div className="flex items-center justify-between"><CardTitle>{account.account_alias}</CardTitle><StatusPill label={account.environment.toUpperCase()} tone={account.environment === "live" ? "bad" : "good"} /></div></CardHeader><CardContent className="space-y-3">{owned.map((profile) => <div key={profile.public_id} className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between"><div><Link className="font-medium hover:underline" href={`/autonomous/${profile.public_id}`}>{profile.name}</Link><p className="mt-1 text-xs text-muted-foreground">{profile.execution_mode} · {schedules.filter((s) => s.profile_ref === profile.public_id && s.enabled).length} active schedule(s)</p>{profileStatus[profile.public_id] && <p className="mt-1 text-xs font-medium">{profileStatus[profile.public_id]}</p>}</div><div className="flex flex-wrap items-center gap-2"><Switch aria-label={`${profile.enabled ? "Disable" : "Enable"} ${profile.name}`} checked={profile.enabled} disabled={Boolean(busy)} onCheckedChange={(value) => toggleProfile(profile, value)} /><Button size="sm" variant="outline" onClick={() => verifyProfile(profile)} disabled={Boolean(busy)}>Verify status</Button><Button asChild size="sm" variant="outline"><Link href={`/autonomous/${profile.public_id}`}>Edit V2</Link></Button><Button size="sm" variant="ghost" className="text-red-600" onClick={() => setDeleteProfile(profile)}>Delete</Button></div></div>)}{!owned.length && <p className="text-sm text-muted-foreground">No profiles for this account.</p>}</CardContent></Card> })}{!accounts.length && <EmptyState title="No broker accounts" description="Connect and select a TradeLocker account before creating an execution profile." />}</div></section>
    <Card><CardHeader><CardTitle>Recent decisions</CardTitle></CardHeader><CardContent className="space-y-2">{runs.slice(0, 8).map((run) => <Link href="/activity" key={run.run_id} className="flex justify-between rounded-lg border p-3 text-sm hover:bg-accent"><span>{run.outcome ?? "Unknown"} · {run.chosen_instrument ?? "No instrument"}</span><span className="text-muted-foreground">{run.status ?? "unknown"}</span></Link>)}{!runs.length && <p className="text-sm text-muted-foreground">No autonomous decisions have been recorded.</p>}</CardContent></Card>
    <Dialog open={liveOpen} onOpenChange={setLiveOpen}><DialogContent><DialogHeader><DialogTitle>Enable live autonomous trading</DialogTitle><DialogDescription>This control can affect real funds only if the backend capability permits it. Type <strong>{LIVE_PHRASE}</strong> exactly.</DialogDescription></DialogHeader><Label htmlFor="live-confirmation">Confirmation phrase</Label><Input id="live-confirmation" value={livePhrase} onChange={(e) => setLivePhrase(e.target.value)} autoComplete="off" /><DialogFooter><Button variant="outline" onClick={() => setLiveOpen(false)}>Cancel</Button><Button disabled={livePhrase !== LIVE_PHRASE || !controls.live_execution_supported} onClick={() => { setLiveOpen(false); void patch({ live_autonomous_enabled: true, live_confirmation: livePhrase }) }}>Enable live autonomy</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><form onSubmit={create}><DialogHeader><DialogTitle>Create execution profile</DialogTitle><DialogDescription>The profile starts in read-only mode and can be configured through the V2 editor.</DialogDescription></DialogHeader><div className="my-5 space-y-4"><div><Label htmlFor="profile-name">Profile name</Label><Input id="profile-name" name="name" required maxLength={64} className="mt-1.5" /></div><div><Label htmlFor="profile-account">Account</Label><select id="profile-account" name="account_id" className="mt-1.5 h-10 w-full rounded-md border bg-background px-3">{accounts.map((a) => <option key={a.public_id} value={a.public_id}>{a.account_alias} · {a.environment}</option>)}</select></div></div><DialogFooter><Button type="button" variant="outline" onClick={() => setCreateOpen(false)}>Cancel</Button><Button disabled={Boolean(busy)}>Create safely</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={Boolean(deleteProfile)} onOpenChange={(value) => !value && setDeleteProfile(null)}><DialogContent><DialogHeader><DialogTitle>Delete {deleteProfile?.name}</DialogTitle><DialogDescription>This also disables its schedule. Type the exact profile name to continue.</DialogDescription></DialogHeader><Input value={confirmation} onChange={(e) => setConfirmation(e.target.value)} aria-label="Profile name confirmation" autoComplete="off" /><DialogFooter><Button variant="outline" onClick={() => setDeleteProfile(null)}>Cancel</Button><Button variant="destructive" disabled={confirmation !== deleteProfile?.name || Boolean(busy)} onClick={remove}>Delete profile</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
function Control({ title, detail, checked, disabled, onChange }: { title: string; detail: string; checked: boolean; disabled: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-5 py-4 first:pt-0 last:pb-0"><div><h3 className="text-sm font-medium">{title}</h3><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><Switch checked={checked} disabled={disabled} onCheckedChange={onChange} aria-label={title} /></div> }
