"use client"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { FormEvent,useState } from "react"
import { Plus,ShieldAlert } from "lucide-react"
import type { Account,AutonomousControls,AutonomousRun,ProfileSummary,Schedule } from "@/lib/afd/contracts"
import { accountLabel,formatEnum } from "@/lib/afd/display"
import { BrowserAfdError,browserAfdFetch,mutateAfd } from "@/lib/afd/browser-client"
import { updateControlsWithRollback } from "@/lib/afd/autonomous"
import { StatusPill } from "@/components/desk/status-pill"
import { EmptyState } from "@/components/desk/page-header"
import { Button } from "@/components/ui/button"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
const LIVE_PHRASE="ENABLE LIVE AUTONOMY"
export function AutonomousWorkspace({initialControls,accounts,profiles,schedules,runs,degraded}:{initialControls:AutonomousControls;accounts:Account[];profiles:ProfileSummary[];schedules:Schedule[];runs:AutonomousRun[];degraded:boolean}){const router=useRouter();const [controls,setControls]=useState(initialControls);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [createOpen,setCreateOpen]=useState(false);const [liveOpen,setLiveOpen]=useState(false);const [phrase,setPhrase]=useState("");const [statuses,setStatuses]=useState<Record<string,string>>({});async function patch(value:object){const previous=controls;setBusy("controls");try{await updateControlsWithRollback(previous,value,setControls,mutateAfd<AutonomousControls>);router.refresh()}catch(e){setError(e instanceof BrowserAfdError?e.message:"Safety state was restored.")}finally{setBusy("")}}async function toggle(profile:ProfileSummary,enabled:boolean){setBusy(profile.public_id);try{await mutateAfd(`execution-profiles/${profile.public_id}`,"PATCH",{enabled});router.refresh()}finally{setBusy("")}}async function verify(profile:ProfileSummary){const data=await browserAfdFetch<{autonomous_active?:boolean;blocking_reasons?:string[]}>(`execution-profiles/${profile.public_id}/autonomy/status`);setStatuses(v=>({...v,[profile.public_id]:data.autonomous_active?"Autonomous active":data.blocking_reasons?.map(formatEnum).join(", ")||"Eligible"}))}async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);await mutateAfd("execution-profiles","POST",{name:data.get("name"),account_id:data.get("account_id"),execution_mode:"read_only"});setCreateOpen(false);router.refresh()}
return <div className="space-y-6">{(degraded||error)&&<p role="alert" className="rounded border border-amber-500/30 p-3 text-sm">{error||"Some automation data is unavailable; unknown state remains blocked."}</p>}<Card><CardHeader><CardTitle className="flex gap-2"><ShieldAlert className="h-5 w-5"/>Global safety controls</CardTitle></CardHeader><CardContent className="divide-y"><Control title="Global kill switch" detail="Blocks all new autonomous submissions." checked={controls.global_autonomous_kill_switch} disabled={Boolean(busy)} onChange={value=>void patch({global_autonomous_kill_switch:value})}/><Control title="Demo autonomous trading" detail={`Effective state: ${formatEnum(controls.effective.demo)}`} checked={controls.demo_autonomous_enabled} disabled={Boolean(busy)||controls.global_autonomous_kill_switch} onChange={value=>void patch({demo_autonomous_enabled:value})}/><Control title="Live autonomous trading" detail={controls.live_execution_supported?`Effective state: ${formatEnum(controls.effective.live)}`:"Live autonomous execution is unsupported."} checked={controls.live_autonomous_enabled} disabled={Boolean(busy)||!controls.live_execution_supported} onChange={value=>value?setLiveOpen(true):void patch({live_autonomous_enabled:false})}/></CardContent></Card>
<section><div className="mb-4 flex justify-between"><div><h2 className="text-xl font-semibold">Execution profiles</h2><p className="text-sm text-muted-foreground">Account-bound automation strategies and risk controls.</p></div><Button onClick={()=>setCreateOpen(true)} disabled={!accounts.length}><Plus className="mr-2 h-4 w-4"/>Create profile</Button></div><div className="space-y-3">{profiles.map(profile=>{const account=accounts.find(item=>item.account_alias===profile.account_alias||item.public_id===profile.account_id);return <Card key={profile.public_id}><CardContent className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="min-w-0"><Link href={`/autonomous/${profile.public_id}`} className="text-lg font-semibold hover:underline">{profile.name}</Link><p className="text-sm text-muted-foreground">{account?accountLabel(account):`${profile.broker_name??"Broker"} · ${profile.account_number??profile.account_alias} · ${formatEnum(profile.account_environment??"account")}`}</p><p className="mt-1 text-xs text-muted-foreground">{formatEnum(profile.execution_mode)} · {schedules.filter(schedule=>schedule.profile_ref===profile.public_id&&schedule.enabled).length} active schedules</p>{statuses[profile.public_id]&&<p className="mt-1 text-xs">{statuses[profile.public_id]}</p>}</div><div className="flex flex-wrap items-center gap-2"><Switch checked={profile.enabled} onCheckedChange={value=>void toggle(profile,value)} aria-label={`Enable ${profile.name}`}/><DemoTest profile={profile} disabled={account?.environment!=="demo"}/><Button size="sm" variant="outline" onClick={()=>void verify(profile)}>Verify</Button><Button asChild size="sm" variant="outline"><Link href={`/autonomous/${profile.public_id}`}>Edit</Link></Button></div></CardContent></Card>})}{!profiles.length&&<EmptyState title="No execution profiles" description={accounts.length?"Create a profile to configure autonomous trading.":"Add a connection and select a primary account."}/>}</div></section>
<Card><CardHeader><CardTitle>Recent decisions</CardTitle></CardHeader><CardContent className="space-y-2">{runs.slice(0,8).map(run=><Link href="/activity" key={run.run_id} className="flex justify-between rounded border p-3 text-sm"><span>{formatEnum(run.outcome)} · {run.chosen_instrument??"No instrument"}</span><span>{formatEnum(run.status)}</span></Link>)}</CardContent></Card>
<Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><form onSubmit={create}><DialogHeader><DialogTitle>Create execution profile</DialogTitle><DialogDescription>Profiles start read-only.</DialogDescription></DialogHeader><div className="my-5 space-y-3"><Label>Profile name</Label><Input name="name" required/><Label>Trading account</Label><select name="account_id" className="h-10 w-full rounded border bg-background px-3">{accounts.map(account=><option value={account.public_id} key={account.public_id}>{accountLabel(account)}</option>)}</select></div><DialogFooter><Button>Create safely</Button></DialogFooter></form></DialogContent></Dialog>
<Dialog open={liveOpen} onOpenChange={setLiveOpen}><DialogContent><DialogHeader><DialogTitle>Enable live autonomous trading</DialogTitle><DialogDescription>Type {LIVE_PHRASE} exactly.</DialogDescription></DialogHeader><Input value={phrase} onChange={e=>setPhrase(e.target.value)}/><DialogFooter><Button disabled={phrase!==LIVE_PHRASE} onClick={()=>{setLiveOpen(false);void patch({live_autonomous_enabled:true,live_confirmation:phrase})}}>Enable live autonomy</Button></DialogFooter></DialogContent></Dialog></div>}
function Control({title,detail,checked,disabled,onChange}:{title:string;detail:string;checked:boolean;disabled:boolean;onChange:(value:boolean)=>void}){return <div className="flex justify-between py-4"><div><h3 className="text-sm font-medium">{title}</h3><p className="text-xs text-muted-foreground">{detail}</p></div><Switch checked={checked} disabled={disabled} onCheckedChange={onChange} aria-label={title}/></div>}
function DemoTest({profile,disabled}:{profile:ProfileSummary;disabled:boolean}){const [result,setResult]=useState<Record<string,unknown>|null>(null);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);async function run(){setBusy(true);setOpen(true);try{setResult(await mutateAfd<Record<string,unknown>>(`execution-profiles/${profile.public_id}/demo-test`,"POST"))}catch(error){setResult({status:"failed",reason_codes:[error instanceof Error?error.message:"Demo test failed"]})}finally{setBusy(false)}}const validation=result?.validation as {approved?:boolean;reasons?:unknown[];would_trade?:boolean}|undefined;const riskChecks=validation?.reasons?.length?validation.reasons.map(value=>formatEnum(String(value))).join(", "):validation?.approved===true?"Passed":validation?.approved===false?"Blocked":"Unavailable";return <><Button size="sm" variant="outline" disabled={disabled||busy} title={disabled?"A demo trading account is required.":undefined} onClick={()=>void run()}>Run Demo Test</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Demo Test · {profile.name}</DialogTitle><DialogDescription>Analysis only. No order can be submitted by this endpoint.</DialogDescription></DialogHeader>{busy?<p>Running saved strategy analysis…</p>:result&&<div className="space-y-3 text-sm"><Result label="Outcome" value={formatEnum(String(result.outcome??result.status))}/><Result label="Selected instrument" value={String(result.symbol??"None")}/><Result label="Confidence" value={String((result.decision as Record<string,unknown>|undefined)?.confidence??"Unavailable")}/><Result label="Blocking reasons" value={Array.isArray(result.reason_codes)?result.reason_codes.map(value=>formatEnum(String(value))).join(", ")||"None":"None"}/><Result label="Risk checks" value={riskChecks}/><Result label="What would happen" value={validation?.would_trade?"A trade candidate passed analysis, but no order was submitted.":String(result.message??"No order was submitted.")}/></div>}</DialogContent></Dialog></>}
function Result({label,value}:{label:string;value:string}){return <div className="rounded border p-3"><p className="text-xs text-muted-foreground">{label}</p><p>{value}</p></div>}
