"use client"
import { useState } from "react"
import { useRouter } from "next/navigation"
import { AlertTriangle, CheckCircle2, Save } from "lucide-react"
import type { ExecutionProfileV2, ProfileContract } from "@/lib/afd/contracts"
import { buildProfilePatch, validateProfile } from "@/lib/afd/profile"
import { BrowserAfdError, mutateAfd } from "@/lib/afd/browser-client"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { StatusPill } from "@/components/desk/status-pill"

type Path = string
function setPath(profile: ExecutionProfileV2, path: Path, value: unknown): ExecutionProfileV2 { const clone = structuredClone(profile) as unknown as Record<string, unknown>; const keys = path.split("."); let target = clone; keys.slice(0, -1).forEach((key) => { target = target[key] as Record<string, unknown> }); target[keys.at(-1)!] = value; return clone as unknown as ExecutionProfileV2 }
function getPath(profile: ExecutionProfileV2, path: Path): unknown { return path.split(".").reduce<unknown>((value, key) => (value as Record<string, unknown>)[key], profile) }

export function ProfileEditor({ contract }: { contract: ProfileContract }) {
  const router = useRouter(); const [profile, setProfile] = useState(contract.profile); const [original, setOriginal] = useState(contract.profile); const [errors, setErrors] = useState<Record<string, string>>({}); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false)
  const update = (path: Path, value: unknown) => setProfile((current) => setPath(current, path, value))
  async function save() { const validation = validateProfile(profile); setErrors(validation); setMessage(""); if (Object.keys(validation).length) return; const patch = buildProfilePatch(original, profile); if (!Object.keys(patch).length) { setMessage("No changes to save."); return } setBusy(true); try { const result = await mutateAfd<ProfileContract>(`execution-profiles/${contract.profile_id}`, "PATCH", patch); setProfile(result.profile); setOriginal(result.profile); setMessage("Backend confirmed the profile update."); router.refresh() } catch (caught) { if (caught instanceof BrowserAfdError) { const detail = caught.payload.detail as { fields?: Array<{ loc?: string[]; msg?: string }> } | undefined; const mapped = Object.fromEntries((detail?.fields ?? []).map((item) => [(item.loc ?? []).filter((key) => key !== "body").join("."), item.msg ?? "Invalid value"])); setErrors(mapped); setMessage(caught.message) } else setMessage("The backend did not confirm this update.") } finally { setBusy(false) } }
  return <div className="space-y-5">{contract.warnings.map((warning) => <div key={warning.code} className="flex gap-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm"><AlertTriangle className="h-5 w-5 shrink-0" /><span>{warning.message}</span></div>)}<div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-card p-4"><div className="flex items-center gap-3"><StatusPill label={`Schema v${profile.schema_version}`} tone="good" /><StatusPill label={contract.migration.state} /><span className="text-sm text-muted-foreground">Account: {contract.account_alias}</span></div><div className="flex items-center gap-3"><label className="flex items-center gap-2 text-sm"><Switch checked={profile.enabled} onCheckedChange={(value) => update("enabled", value)} /> Profile enabled</label><Button onClick={save} disabled={busy}><Save className="mr-2 h-4 w-4" />{busy ? "Saving…" : "Save V2 profile"}</Button></div></div>{message && <p role="status" className="flex items-center gap-2 rounded-lg border p-3 text-sm"><CheckCircle2 className="h-4 w-4" />{message}</p>}
    <Section title="Trading policy" description="Decision behavior and confidence floor."><Select profile={profile} path="trading_policy.mode" label="Policy mode" options={["adaptive", "preset"]} update={update} /><Select profile={profile} path="trading_policy.preset_id" label="Preset ID" options={["hourly_forex"]} update={update} disabled={profile.trading_policy.mode !== "preset"} error={errors["trading_policy.preset_id"]} /><Field profile={profile} path="trading_policy.decision_interval" label="Decision interval" disabled update={update} /><NumberField profile={profile} path="trading_policy.minimum_confidence" label="Minimum confidence" min={0} max={1} step={0.01} update={update} error={errors["trading_policy.minimum_confidence"]} /></Section>
    <Section title="Market universe" description="The canonical broker instruments this profile may consider."><Select profile={profile} path="market_universe.mode" label="Universe mode" options={["all_available", "groups", "custom"]} update={update} /><ListField label="Market groups" value={profile.market_universe.groups} options={contract.available_market_groups} disabled={profile.market_universe.mode !== "groups"} onChange={(value) => update("market_universe.groups", value)} error={errors["market_universe.groups"]} /><TextList label="Included instrument IDs" value={profile.market_universe.included_instrument_ids} disabled={profile.market_universe.mode !== "custom"} onChange={(value) => update("market_universe.included_instrument_ids", value)} error={errors["market_universe.included_instrument_ids"]} /><TextList label="Excluded instrument IDs" value={profile.market_universe.excluded_instrument_ids} onChange={(value) => update("market_universe.excluded_instrument_ids", value)} /></Section>
    <Section title="Risk policy" description="All values remain subject to backend validation and pre-trade enforcement."><Select profile={profile} path="risk_policy.mode" label="Risk mode" options={["fixed", "adaptive"]} update={update} />{[["fixed_risk_pct","Fixed risk %"],["base_risk_pct","Base risk %"],["minimum_risk_pct","Minimum risk %"],["maximum_risk_pct","Maximum risk %"],["maximum_total_open_risk_pct","Max total open risk %"],["maximum_margin_utilization_pct","Max margin utilization %"],["maximum_correlated_risk_pct","Max correlated risk %"],["daily_loss_limit_pct","Daily loss limit %"],["drawdown_cutoff_pct","Drawdown cutoff %"],["maximum_open_positions","Max open positions"],["maximum_pending_entry_orders","Max pending entries"],["maximum_new_entries_per_day","Max new entries/day"]].map(([key,label]) => <NumberField key={key} profile={profile} path={`risk_policy.${key}`} label={label} step={key.includes("positions") || key.includes("entries") ? 1 : .01} update={update} error={errors[`risk_policy.${key}`]} />)}</Section>
    <Section title="Capital allocation" description="Controls which capital base the risk policy can use."><Select profile={profile} path="capital_allocation.mode" label="Allocation mode" options={["full_account", "fixed_amount", "equity_percentage"]} update={update} /><NumberField profile={profile} path="capital_allocation.fixed_amount" label="Fixed amount" disabled={profile.capital_allocation.mode !== "fixed_amount"} update={update} error={errors["capital_allocation.fixed_amount"]} /><NumberField profile={profile} path="capital_allocation.equity_percentage" label="Equity percentage" disabled={profile.capital_allocation.mode !== "equity_percentage"} update={update} error={errors["capital_allocation.equity_percentage"]} /><Select profile={profile} path="capital_allocation.risk_base" label="Risk base" options={["account_equity", "allocated_capital"]} update={update} /><Select profile={profile} path="capital_allocation.compounding_mode" label="Compounding" options={["disabled", "realized_pnl", "periodic_rebalance"]} update={update} /><NumberField profile={profile} path="capital_allocation.maximum_margin_utilization_pct" label="Max margin utilization %" update={update} /><NumberField profile={profile} path="capital_allocation.maximum_gross_exposure_multiple" label="Max gross exposure multiple" update={update} /><Toggle profile={profile} path="capital_allocation.allow_shared_capital" label="Allow shared capital" update={update} /></Section>
    <Section title="Exit policy" description="Protective orders, trailing behavior, and break-even configuration."><Toggle profile={profile} path="exit_policy.stop_loss.enabled" label="Stop loss enabled" update={update} /><Select profile={profile} path="exit_policy.stop_loss.mode" label="Stop mode" options={["adaptive_structure", "volatility", "fixed_distance", "fixed_percentage"]} update={update} /><NumberField profile={profile} path="exit_policy.stop_loss.fixed_distance" label="Fixed distance" update={update} /><NumberField profile={profile} path="exit_policy.stop_loss.fixed_percentage" label="Fixed percentage" update={update} /><NumberField profile={profile} path="exit_policy.stop_loss.maximum_risk_distance" label="Maximum risk distance" update={update} /><Toggle profile={profile} path="exit_policy.take_profit.enabled" label="Take profit enabled" update={update} /><Select profile={profile} path="exit_policy.take_profit.mode" label="Take-profit mode" options={["reward_to_risk", "adaptive_structure", "trailing_only", "none"]} update={update} /><NumberField profile={profile} path="exit_policy.take_profit.minimum_reward_to_risk" label="Minimum reward-to-risk" update={update} /><NumberField profile={profile} path="exit_policy.take_profit.target_reward_to_risk" label="Target reward-to-risk" update={update} error={errors["exit_policy.take_profit.target_reward_to_risk"]} /><Toggle profile={profile} path="exit_policy.trailing_stop.enabled" label="Trailing stop enabled" update={update} /><Select profile={profile} path="exit_policy.trailing_stop.activation_mode" label="Trailing activation" options={["reward_multiple", "fixed_distance", "percentage"]} update={update} /><NumberField profile={profile} path="exit_policy.trailing_stop.activation_value" label="Activation value" update={update} /><NumberField profile={profile} path="exit_policy.trailing_stop.trail_value" label="Trail value" update={update} /><Toggle profile={profile} path="exit_policy.break_even.enabled" label="Break-even enabled" update={update} /><NumberField profile={profile} path="exit_policy.break_even.activation_reward_multiple" label="Break-even activation R" update={update} /><NumberField profile={profile} path="exit_policy.break_even.offset" label="Break-even offset" update={update} /><div className="col-span-full rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-sm"><strong>Partial exits are not execution-supported.</strong><p className="mt-1 text-muted-foreground">The backend reports this limitation explicitly; configuration is disabled.</p></div></Section>
    <Section title="Schedule policy" description="Profile policy only. The persistent backend worker owns durable execution."><Field profile={profile} path="schedule_policy.timezone" label="Timezone" update={update} /><TextList label="Local run times" value={profile.schedule_policy.times} onChange={(value) => update("schedule_policy.times", value)} placeholder="05:00, 09:00" /><Toggle profile={profile} path="schedule_policy.market_aware" label="Market-aware behavior" update={update} /><Toggle profile={profile} path="schedule_policy.run_when_any_selected_market_is_open" label="Run when any selected market is open" update={update} /></Section>
  </div>
}
function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle><p className="text-sm text-muted-foreground">{description}</p></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{children}</CardContent></Card> }
type BaseProps = { profile: ExecutionProfileV2; path: Path; label: string; update: (path: Path, value: unknown) => void; disabled?: boolean; error?: string }
function Field({ profile, path, label, update, disabled, error }: BaseProps) { return <div><Label>{label}</Label><Input className="mt-1.5" value={String(getPath(profile, path) ?? "")} disabled={disabled} onChange={(e) => update(path, e.target.value)} aria-invalid={Boolean(error)} />{error && <p className="mt-1 text-xs text-red-600">{error}</p>}</div> }
function NumberField({ profile, path, label, update, disabled, error, min, max, step = .01 }: BaseProps & { min?: number; max?: number; step?: number }) { const value = getPath(profile, path); return <div><Label>{label}</Label><Input type="number" className="mt-1.5" value={value == null ? "" : String(value)} disabled={disabled} min={min} max={max} step={step} onChange={(e) => update(path, e.target.value === "" ? null : Number(e.target.value))} aria-invalid={Boolean(error)} />{error && <p className="mt-1 text-xs text-red-600">{error}</p>}</div> }
function Select({ profile, path, label, options, update, disabled, error }: BaseProps & { options: string[] }) { return <div><Label>{label}</Label><select className="mt-1.5 h-10 w-full rounded-md border bg-background px-3 text-sm" value={String(getPath(profile, path) ?? "")} disabled={disabled} onChange={(e) => update(path, e.target.value)}>{options.map((option) => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select>{error && <p className="mt-1 text-xs text-red-600">{error}</p>}</div> }
function Toggle({ profile, path, label, update }: BaseProps) { return <label className="flex min-h-10 items-center justify-between gap-3 rounded-md border px-3 text-sm"><span>{label}</span><Switch checked={Boolean(getPath(profile, path))} onCheckedChange={(value) => update(path, value)} /></label> }
function TextList({ label, value, onChange, disabled, error, placeholder = "Comma-separated IDs" }: { label: string; value: string[]; onChange: (value: string[]) => void; disabled?: boolean; error?: string; placeholder?: string }) { return <div><Label>{label}</Label><Input className="mt-1.5" disabled={disabled} value={value.join(", ")} placeholder={placeholder} onChange={(e) => onChange(e.target.value.split(",").map((item) => item.trim()).filter(Boolean))} aria-invalid={Boolean(error)} />{error && <p className="mt-1 text-xs text-red-600">{error}</p>}</div> }
function ListField({ label, value, options, onChange, disabled, error }: { label: string; value: string[]; options: string[]; onChange: (value: string[]) => void; disabled?: boolean; error?: string }) { return <div className="sm:col-span-2"><Label>{label}</Label><div className="mt-2 flex flex-wrap gap-2">{options.map((option) => <label key={option} className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" disabled={disabled} checked={value.includes(option)} onChange={(e) => onChange(e.target.checked ? [...value, option] : value.filter((item) => item !== option))} />{option}</label>)}</div>{error && <p className="mt-1 text-xs text-red-600">{error}</p>}</div> }
