"use client"

import {useMemo,useState} from "react"
import {Copy,ExternalLink,Unplug} from "lucide-react"
import type {McpAuthorizedClient,McpPermission,McpSettings} from "@/lib/afd/contracts"
import {activeAuthorizedClient,chatGptConnectionStatus,copyPublicUrl} from "@/lib/afd/mcp"
import {mutateAfd} from "@/lib/afd/browser-client"
import {ChatGptSetupInstructions} from "@/components/settings/chatgpt-setup-instructions"
import {StatusPill} from "@/components/desk/status-pill"
import {Button} from "@/components/ui/button"
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card"
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from "@/components/ui/alert-dialog"

export function McpConnectionSettings({initialSettings}:{initialSettings:McpSettings|null}){
  const [settings,setSettings]=useState(initialSettings);const [copied,setCopied]=useState("");const [disconnect,setDisconnect]=useState<McpAuthorizedClient|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("")
  const status=chatGptConnectionStatus(settings);const active=activeAuthorizedClient(settings?.authorized_clients??null)
  const labels=useMemo(()=>new Map(settings?.supported_scopes.map(item=>[item.scope,item.label])??[]),[settings])
  async function copy(url:string,label="MCP URL copied."){try{const result=await copyPublicUrl(navigator.clipboard,url);setCopied(label==="MCP URL copied."?result:label)}catch{setCopied("Copy failed. Select and copy the URL manually.")}}
  async function revoke(){if(!disconnect)return;setBusy(true);setMessage("");try{await mutateAfd(`integrations/mcp/authorized-clients/${disconnect.grant_id}/revoke`,"POST");setSettings(current=>current?{...current,authorized_clients:current.authorized_clients?.map(item=>item.grant_id===disconnect.grant_id?{...item,status:"revoked"}:item)??null}:current);setMessage("ChatGPT disconnected.");setDisconnect(null)}catch{setMessage("ChatGPT could not be disconnected. Try again.")}finally{setBusy(false)}}
  if(!settings)return <Card><CardContent className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Connection information unavailable</h2><p className="text-sm text-muted-foreground">The ChatGPT connection settings could not be loaded.</p></div><StatusPill label="Unavailable" tone="bad"/></div></CardContent></Card>
  const granted=new Set(active?.granted_scopes??[])
  return <div className="space-y-5">
    <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="text-lg">ChatGPT Connection</CardTitle><StatusPill label={status} tone={status==="Connected"?"good":status==="Needs Attention"||status==="Authorization Expired"?"warn":"neutral"}/></div></CardHeader><CardContent className="space-y-5">
      <div className="grid min-w-0 gap-4 sm:grid-cols-2"><Datum label="Status" value={status}/><Datum label="Authentication" value={settings.authentication_required?(settings.authentication_available?"Required and available":"Required; needs attention"):"Not required"}/><div className="min-w-0 sm:col-span-2"><p className="text-xs text-muted-foreground">MCP server URL</p><code className="block break-all rounded bg-muted p-3 text-sm">{settings.server_url}</code></div></div>
      <div className="flex flex-wrap gap-2"><Button onClick={()=>void copy(settings.server_url)}><Copy/>Copy MCP URL</Button>{settings.setup_url&&<Button asChild variant="outline"><a href={settings.setup_url} target="_blank" rel="noreferrer">Open ChatGPT Settings<ExternalLink/></a></Button>}</div><p role="status" className="text-sm text-muted-foreground">{copied}</p>
      <ChatGptSetupInstructions/>
    </CardContent></Card>
    <Card><CardHeader><CardTitle className="text-lg">Permission summary</CardTitle></CardHeader><CardContent className="space-y-3">{settings.supported_scopes.map(permission=><PermissionRow key={permission.scope} permission={permission} state={active?(granted.has(permission.scope)?"Granted":"Not Granted"):"Available"}/>)}{settings.unsupported_scopes.map(permission=><PermissionRow key={permission.scope} permission={permission} state="Unsupported"/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-lg">Authorized applications</CardTitle></CardHeader><CardContent className="space-y-4">{settings.authorized_clients_status==="unavailable"?<p className="text-sm text-muted-foreground">Authorized application management will be available after the security upgrade.</p>:settings.authorized_clients?.length?settings.authorized_clients.map(client=><div key={client.grant_id} className="grid min-w-0 gap-3 rounded-lg border p-4 sm:grid-cols-[1fr_auto]"><div className="min-w-0 space-y-2"><div className="flex flex-wrap items-center gap-2"><strong>{client.client_name}</strong><StatusPill label={client.status==="active"?"Active":client.status==="revoked"?"Revoked":"Authorization Expired"} tone={client.status==="active"?"good":client.status==="revoked"?"neutral":"warn"}/></div><p className="text-sm text-muted-foreground">Connected {date(client.connected_at)} · Last used {date(client.last_used_at)}</p><p className="text-sm">Granted permissions: {client.granted_scopes.map(scope=>labels.get(scope)??"Permission unavailable").join(", ")||"None"}</p></div>{client.status==="active"&&settings.revocation_supported&&<Button variant="outline" onClick={()=>setDisconnect(client)}><Unplug/>Disconnect</Button>}</div>):<p className="text-sm text-muted-foreground">No ChatGPT applications are currently authorized.</p>}<p role="status" className="text-sm">{message}</p></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-lg">Connection diagnostics</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Datum label="MCP Service" value={settings.status==="available"?"Available":"Needs Attention"}/><Datum label="Authentication" value={settings.authentication_available?"Available":"Needs Attention"}/><Datum label="ChatGPT Authorization" value={status}/><Datum label="Last Successful Use" value={date(active?.last_used_at)}/><Datum label="Permissions Granted" value={String(active?.granted_scopes.length??0)}/></CardContent></Card>
    <details className="rounded-lg border bg-card"><summary className="cursor-pointer p-5 font-semibold">Advanced Details</summary><div className="grid min-w-0 gap-4 border-t p-5 text-sm sm:grid-cols-2"><PublicUrl label="MCP server URL" value={settings.server_url} onCopy={copy}/><PublicUrl label="MCP resource URI" value={settings.resource_uri} onCopy={copy}/><PublicUrl label="Protected-resource metadata URL" value={settings.protected_resource_metadata_url} onCopy={copy}/><Datum label="Authorization-server issuer" value={settings.authorization_server_issuer}/><Datum label="Supported scopes" value={settings.supported_scopes.map(item=>item.scope).join(", ")}/><Datum label="MCP protocol status" value={settings.protocol_status}/></div></details>
    <AlertDialog open={Boolean(disconnect)} onOpenChange={open=>!open&&setDisconnect(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Disconnect ChatGPT?</AlertDialogTitle><AlertDialogDescription>ChatGPT will no longer be able to access Agentic Trading Desk until you connect it again. Your dashboard and trading connections will remain active.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>void revoke()}>Disconnect ChatGPT</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
}

function PermissionRow({permission,state}:{permission:McpPermission;state:"Available"|"Granted"|"Not Granted"|"Unsupported"}){return <div className="flex flex-col justify-between gap-2 rounded border p-3 sm:flex-row sm:items-center"><div><strong className="text-sm">{permission.label}</strong><p className="text-sm text-muted-foreground">{permission.description}</p></div><StatusPill label={state} tone={state==="Granted"?"good":state==="Unsupported"?"neutral":"warn"}/></div>}
function Datum({label,value}:{label:string;value:string}){return <div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="break-words font-medium">{value}</p></div>}
function PublicUrl({label,value,onCopy}:{label:string;value:string;onCopy:(value:string,label?:string)=>Promise<void>}){return <div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><code className="block break-all">{value}</code><Button size="sm" variant="ghost" onClick={()=>void onCopy(value,`${label} copied.`)}><Copy/>Copy</Button></div>}
function date(value?:string|null){return value?new Date(value).toLocaleString():"Not recorded"}
