"use client"
import { useState } from "react"
import type { AutonomousRun,DemoExecution,RunAudit } from "@/lib/afd/contracts"
import { formatEnum } from "@/lib/afd/display"
import { browserAfdFetch } from "@/lib/afd/browser-client"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from "@/components/ui/sheet"
import { StatusPill } from "@/components/desk/status-pill"
const when=(value?:unknown)=>typeof value==="string"?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Time not recorded"
export function ActivityWorkspace({runs,executions,controlEvents}:{runs:AutonomousRun[];executions:DemoExecution[];controlEvents:Array<Record<string,unknown>>}){const [audit,setAudit]=useState<RunAudit|null>(null);const [open,setOpen]=useState(false);async function inspect(id:string){setOpen(true);setAudit(await browserAfdFetch<RunAudit>(`autonomous-runs/${id}/audit`))}return <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader><CardTitle>Autonomous runs</CardTitle></CardHeader><CardContent className="space-y-2">{runs.map(run=><button key={run.run_id} onClick={()=>void inspect(run.run_id)} className="flex w-full justify-between rounded border p-3 text-left"><span><strong>{formatEnum(run.outcome)}</strong><small className="block">{run.chosen_instrument??"No instrument"} · {when(run.started_at)}</small></span><StatusPill label={formatEnum(run.status)}/></button>)}</CardContent></Card><div className="space-y-5"><Card><CardHeader><CardTitle>Demo executions</CardTitle></CardHeader><CardContent className="space-y-2">{executions.map(item=><div className="rounded border p-3" key={item.id}><strong>{formatEnum(item.action_type??item.symbol)}</strong><p className="text-xs text-muted-foreground">{formatEnum(item.state??item.result)} · {when(item.created_at)}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Safety control history</CardTitle></CardHeader><CardContent className="space-y-2">{controlEvents.slice(0,10).map((event,index)=><div className="rounded border p-3 text-sm" key={String(event.id??index)}><strong>{formatEnum(String(event.control_name??event.source??"Safety control change"))}</strong><p className="text-xs text-muted-foreground">{when(event.occurred_at)}</p></div>)}</CardContent></Card></div><Sheet open={open} onOpenChange={setOpen}><SheetContent className="overflow-y-auto sm:max-w-xl"><SheetHeader><SheetTitle>Run audit</SheetTitle><SheetDescription>Structured backend decision audit.</SheetDescription></SheetHeader>{audit&&<div className="mt-6 space-y-3"><Datum label="Outcome" value={formatEnum(audit.outcome)}/><Datum label="Selected markets" value={audit.selected_market_universe.join(", ")||"None"}/><Datum label="Markets open" value={audit.markets_currently_open.join(", ")||"None"}/><Datum label="Chosen instrument" value={audit.chosen_instrument??"None"}/><Datum label="Reason codes" value={audit.reason_codes.map(formatEnum).join(", ")||"None"}/><Button variant="outline" onClick={()=>setOpen(false)}>Close</Button></div>}</SheetContent></Sheet></div>}
function Datum({label,value}:{label:string;value:string}){return <div className="rounded border p-3"><p className="text-xs text-muted-foreground">{label}</p><p>{value}</p></div>}
